#coding:utf-8

"""
ID:          n/a
TITLE:       LOCAL TEMPORARY TABLE - verify restrictions.
DESCRIPTION:
    Test verifies restrictions defined for LTT in doc/sql.extensions/README.local_temporary_tables.md
NOTES:
    [08.02.2026] pzotov
    Checked on 6.0.0.1405-761a49d.
"""
import locale
from pathlib import Path
from firebird.driver import DatabaseError
import pytest
from firebird.qa import *

init_sql = """
    set bail on;
    set autoterm on;
    recreate table ddl_log (
        id integer generated by default as identity constraint pk_ddl_log primary key using index pk_ddl_log
        ,who_logs varchar(50)
        ,evn_type varchar(50)
        ,obj_type varchar(50)
        ,obj_name varchar(50)
        ,old_name varchar(50)
        ,new_name varchar(50)
        ,sql_text blob sub_type text
    );
    commit;
    execute block as
    begin
        rdb$set_context('USER_SESSION', 'INIT_DDL', 1);
    end;

    -- active before create domain or alter domain or drop domain
    create trigger ddl_log_befo active before any ddl statement
    as
    begin
        if ( rdb$get_context('USER_SESSION', 'INIT_DDL') is null ) then
        begin
            insert into ddl_log(
               who_logs
              ,evn_type
              ,obj_type
              ,obj_name
              ,old_name
              ,new_name
              ,sql_text
            ) values (
               'DDL trigger BEFORE ddl statement'
              ,rdb$get_context('DDL_TRIGGER', 'EVENT_TYPE')
              ,rdb$get_context('DDL_TRIGGER', 'OBJECT_TYPE')
              ,rdb$get_context('DDL_TRIGGER', 'OBJECT_NAME')
              ,rdb$get_context('DDL_TRIGGER', 'OLD_OBJECT_NAME')
              ,rdb$get_context('DDL_TRIGGER', 'NEW_OBJECT_NAME')
              ,rdb$get_context('DDL_TRIGGER', 'SQL_TEXT')
            );
        end
    end
    ;

    -- active before create domain or alter domain or drop domain
    create trigger ddl_log_afte active after any ddl statement
    as
    begin
        if ( rdb$get_context('USER_SESSION', 'INIT_DDL') is null ) then
        begin
            in autonomous transaction do
            insert into ddl_log(
               who_logs
              ,evn_type
              ,obj_type
              ,obj_name
              ,old_name
              ,new_name
              ,sql_text
            ) values (
               'DDL trigger AFTER ddl statement'
               ,rdb$get_context('DDL_TRIGGER', 'EVENT_TYPE')
              ,rdb$get_context('DDL_TRIGGER', 'OBJECT_TYPE')
              ,rdb$get_context('DDL_TRIGGER', 'OBJECT_NAME')
              ,rdb$get_context('DDL_TRIGGER', 'OLD_OBJECT_NAME')
              ,rdb$get_context('DDL_TRIGGER', 'NEW_OBJECT_NAME')
              ,rdb$get_context('DDL_TRIGGER', 'SQL_TEXT')
            );
        end
    end
    ;
    commit;
"""

db = db_factory(init = init_sql)

substitutions = [('[ \t]+', ' '), ('(-)?At line .*', '')]
act = python_act('db', substitutions = substitutions)
external_table = temp_file('tmp_ltt.dat')

@pytest.mark.version('>=6.0')
def test_1(act: Action, external_table: Path, capsys):

    # LTT is visible only to the connection that has created it.
    with act.db.connect(no_db_triggers = True) as con1, act.db.connect(no_db_triggers = True) as con2:
        cur1 = con1.cursor()
        cur2 = con2.cursor()
        con1.execute_immediate('create local temporary table ltt_test_1(id int) on commit preserve rows')
        con1.commit()
        con1.execute_immediate('insert into ltt_test_1(id) select n from generate_series(1, 100) as s(n)')
        con1.commit()
        ps, rs =  None, None
        try:
            print('Check-1')
            ps = cur2.prepare('select count(*) from ltt_test_1')
            rs = cur2.fetchall()
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()
        
    act.expected_stdout = """
        Check-1
        Dynamic SQL Error
        -SQL error code = -204
        -Table unknown
        -"LTT_TEST_1"
        (335544569, 335544436, 335544580, 335544382, 336397208)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()

    #-----------------------------------------------------------

    # LTT persists only while connection alive:
    with act.db.connect(no_db_triggers = True) as con1:
        con1.execute_immediate('create local temporary table ltt_test_2(id int) on commit preserve rows')
        con1.commit()
    with act.db.connect(no_db_triggers = True) as con2:
        cur2 = con2.cursor()
        ps, rs =  None, None
        try:
            print('Check-2')
            ps = cur2.prepare('select count(*) from ltt_test_2')
            rs = cur2.fetchall()
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()
        
    act.expected_stdout = """
        Check-2
        Dynamic SQL Error
        -SQL error code = -204
        -Table unknown
        -"LTT_TEST_2"
        (335544569, 335544436, 335544580, 335544382, 336397208)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()


    #-----------------------------------------------------------

    # LTT *can* be created in read-only DB:
    act.gfix(switches=['-mode','read_only', act.db.dsn], combine_output = True, io_enc = locale.getpreferredencoding())
    ps, rs =  None, None
    try:
        print('Check-3')
        with act.db.connect(no_db_triggers = True) as con1:
            con1.execute_immediate('create local temporary table ltt_test_3(id int) on commit preserve rows')
            con1.commit()
            con1.execute_immediate('insert into ltt_test_3(id) select n from generate_series(1, 100) as s(n)')
            con1.commit()
            cur1 = con1.cursor()
            ps = cur1.prepare('select (select count(*) from ltt_test_3) as ltt_test_3_count, mon$read_only from mon$database')
            for r in cur1.execute(ps):
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
    except DatabaseError as e:
        print(e.__str__())
        print(e.gds_codes)
    finally:
        if rs:
            rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
        if ps:
            ps.free()
        act.gfix(switches=['-mode','read_write', act.db.dsn], combine_output = True, io_enc = locale.getpreferredencoding())

    act.expected_stdout = """
        Check-3
        LTT_TEST_3_COUNT: 100
        MON$READ_ONLY: 1
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()

    #-----------------------------------------------------------

    # DDL triggers do not fire when LTT is created / altered /dropped
    with act.db.connect() as con1:
        con1.execute_immediate('create local temporary table ltt_test_4(id int) on commit preserve rows')
        con1.commit()
        cur1 = con1.cursor()
        ps, rs =  None, None
        try:
            print('Check-4')
            cur1.execute('select d.* from rdb$database r left join ddl_log d on 1=1')
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()

    act.expected_stdout = """
        Check-4
        ID: None
        WHO_LOGS: None
        EVN_TYPE: None
        OBJ_TYPE: None
        OBJ_NAME: None
        OLD_NAME: None
        NEW_NAME: None
        SQL_TEXT: None
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()

    #-----------------------------------------------------------

    # DML triggers are not supported for LTT
    with act.db.connect() as con1:
        con1.execute_immediate('create local temporary table ltt_test_5(id int) on commit preserve rows')
        con1.commit()
        cur1 = con1.cursor()
        ps, rs =  None, None
        try:
            print('Check-5')
            con1.execute_immediate('create or alter trigger ltt_test_5_bi for ltt_test_5 active before insert as begin end')
            con1.commit()
            cur1.execute("select rdb$trigger_name as unexpected_trigger_exists from rdb$triggers where rdb$relation_name = upper('ltt_test_5')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()
    
    act.expected_stdout = """
        Check-5
        unsuccessful metadata update
        -CREATE OR ALTER TRIGGER "PUBLIC"."LTT_TEST_5_BI" failed
        -LOCAL TEMPORARY TABLE "PUBLIC"."LTT_TEST_5" cannot be referenced in persistent metadata
        (335544351, 336397272, 336003114)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()

    #-----------------------------------------------------------

    # LTT cannot be referenced in persistent metadata 
    with act.db.connect() as con1:
        con1.execute_immediate('create local temporary table ltt_test_6(id int) on commit preserve rows')
        con1.commit()
        try:
            print('Check-6')
            con1.execute_immediate('create view v_ltt as select * from ltt_test_6')
            con1.commit()
            cur1.execute("select rdb$relation_name as unexpected_db_object_exists from rdb$relations where rdb$relation_name = upper('ltt_test_6')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()
    
    act.expected_stdout = """
        Check-6
        unsuccessful metadata update
        -CREATE VIEW "PUBLIC"."V_LTT" failed
        -LOCAL TEMPORARY TABLE "PUBLIC"."LTT_TEST_6" cannot be referenced in persistent metadata
        (335544351, 336397298, 336003114)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()

    #-----------------------------------------------------------

    # Partial or computed indices not allowed for LTT
    with act.db.connect() as con1:
        con1.execute_immediate('create local temporary table ltt_test_7(id int) on commit preserve rows')
        con1.commit()

        try:
            print('Check-7')
            con1.execute_immediate('create index ltt_test_7_partial on ltt_test_7(id) where mod(id,2) = 0')
            con1.commit()
            cur1.execute("select rdb$index_name as unexpected_db_object_exists from rdb$indices where rdb$relation_name = upper('ltt_test_7')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()

        try:
            print('Check-8')
            con1.execute_immediate('create index ltt_test_7_computed on ltt_test_7 computed by(id * id)')
            con1.commit()
            cur1.execute("select rdb$index_name as unexpected_db_object_exists from rdb$indices where rdb$relation_name = upper('ltt_test_7')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()
                

    act.expected_stdout = """
        Check-7
        unsuccessful metadata update
        -CREATE INDEX "PUBLIC"."LTT_TEST_7_PARTIAL" failed
        -SQL error code = -607
        -feature is not supported
        -Partial indexes are not supported for local temporary tables
        (335544351, 336397316, 335544436, 335544378, 335544382)

        Check-8
        unsuccessful metadata update
        -CREATE INDEX "PUBLIC"."LTT_TEST_7_COMPUTED" failed
        -SQL error code = -607
        -feature is not supported
        -Expression-based indexes are not supported for local temporary tables
        (335544351, 336397316, 335544436, 335544378, 335544382)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()


    #-----------------------------------------------------------

    # PK, FK, CHECK constraints not supported for LTT. Field-level 'not null' *supported*.
    with act.db.connect() as con1:
        con1.execute_immediate('create local temporary table ltt_test_8(id int not null, id2 int, pid int) on commit preserve rows')
        con1.commit()
        con1.execute_immediate('create unique index ltt_test_8_id2_unq on ltt_test_8(id2)') # must PASS
        con1.commit()

        try:
            print('Check-9')
            con1.execute_immediate('alter table ltt_test_8 add constraint ltt_test_8_pk primary key(id)')
            con1.commit()
            cur1.execute("select rdb$index_name as unexpected_db_object_exists from rdb$indices where rdb$relation_name = upper('ltt_test_8')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()

        try:
            print('Check-10')
            con1.execute_immediate('alter table ltt_test_8 add constraint ltt_test_8_fk foreign key(pid) references ltt_test_8_fk(id2)')
            con1.commit()
            cur1.execute("select rdb$index_name as unexpected_db_object_exists from rdb$indices where rdb$relation_name = upper('ltt_test_8')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()

        
        try:
            print('check-11')
            con1.execute_immediate('alter table ltt_test_8 add constraint ltt_test_8_ck check(id > 0)')
            con1.commit()
            cur1.execute("select rdb$constraint_name as unexpected_constraint_exists from rdb$check_constraints where rdb$constraint_name = upper('ltt_test_8_ck')")
            for r in cur1:
                for i,col in enumerate(cur1.description):
                    print((col[0] +':').ljust(32), r[i])
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)
        finally:
            if rs:
                rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
            if ps:
                ps.free()
                

    act.expected_stdout = """
        Check-9
        unsuccessful metadata update
        -ALTER TABLE "PUBLIC"."LTT_TEST_8" failed
        -SQL error code = -607
        -Invalid command
        -Only NOT NULL constraints without names are supported on local temporary tables
        (335544351, 336397287, 335544436, 335544570, 335544382)
        
        Check-10
        unsuccessful metadata update
        -ALTER TABLE "PUBLIC"."LTT_TEST_8" failed
        -SQL error code = -607
        -Invalid command
        -Only NOT NULL constraints without names are supported on local temporary tables
        (335544351, 336397287, 335544436, 335544570, 335544382)
        
        check-11
        unsuccessful metadata update
        -ALTER TABLE "PUBLIC"."LTT_TEST_8" failed
        -SQL error code = -607
        -Invalid command
        -Only NOT NULL constraints without names are supported on local temporary tables
        (335544351, 336397287, 335544436, 335544570, 335544382)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()


    #-----------------------------------------------------------

    # **DEFAULT values**: Columns cannot have default values.
    # **COMPUTED BY columns**: Computed columns are not supported.
    # **IDENTITY columns**: Identity (auto-increment) columns are not supported.
    # **SQL SECURITY clause**: The SQL SECURITY clause is not applicable to LTTs.
    with act.db.connect() as con1:
        try:
            print('Check-12')
            con1.execute_immediate('create local temporary table ltt_test_9(id int default -123)')
            con1.commit()
            print('Column in LTT unexpectedly has DEFAULT value.')
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)

        try:
            print('Check-13')
            con1.execute_immediate('create local temporary table ltt_test_9(id int, id_quad computed by (id*x))')
            con1.commit()
            print('Computed-by column in LTT unexpectedly created.')
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)

        try:
            print('Check-14')
            con1.execute_immediate('create local temporary table ltt_test_9(id int generated by default as identity)')
            con1.commit()
            print('Identity column in LTT unexpectedly created.')
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)

        try:
            print('Check-15')
            con1.execute_immediate("recreate local temporary table ltt_test_10 external file '{str(external_table)}' (uid char(36), lf char(1))")
            con1.commit()
            print('LTT unexpectedly created with link to external files.')
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)

        try:
            print('Check-16')
            con1.execute_immediate("recreate local temporary table ltt_test_11(id int) SQL SECURITY DEFINER")
            con1.commit()
            print('LTT unexpectedly created with SQL SECURITY clause.')
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)

    
    act.expected_stdout = """
        Check-12
        unsuccessful metadata update
        -CREATE TABLE "PUBLIC"."LTT_TEST_9" failed
        -DEFAULT is not allowed for LOCAL TEMPORARY TABLE columns
        (335544351, 336397286, 335544382)

        Check-13
        unsuccessful metadata update
        -CREATE TABLE "PUBLIC"."LTT_TEST_9" failed
        -COMPUTED BY is not allowed for LOCAL TEMPORARY TABLE columns
        (335544351, 336397286, 335544382)

        Check-14
        unsuccessful metadata update
        -CREATE TABLE "PUBLIC"."LTT_TEST_9" failed
        -IDENTITY columns are not allowed for LOCAL TEMPORARY TABLEs
        (335544351, 336397286, 335544382)

        Check-15
        Dynamic SQL Error
        -SQL error code = -104
        -Token unknown - line 1, column 44
        -external
        (335544569, 335544436, 335544634, 335544382)

        Check-16
        Dynamic SQL Error
        -SQL error code = -104
        -Token unknown - line 1, column 52
        -SQL
        (335544569, 335544436, 335544634, 335544382)
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()

