#coding:utf-8

"""
ID:          intfunc.listagg.03
ISSUE:       https://github.com/FirebirdSQL/firebird/pull/8689
TITLE:       LISTAGG(DISTINCT <char>): must remove duplicated characters if they are not distinguish in CI/AI comparison.
DESCRIPTION:
NOTES:
    [20.11.2025] pzotov
    Checked on 6.0.0.1356-df73f92.
"""

import pytest
from firebird.qa import *

db = db_factory(charset = 'utf8')

test_script = """
    set list on;
    set blob all;

	create collation coll_cs_as for utf8 from unicode;
    create collation coll_ci_ai for utf8 from unicode case insensitive accent insensitive;

    create domain dm_name_cs_as varchar(1) character set utf8 collate coll_cs_as;
    create domain dm_name_ci_ai varchar(1) character set utf8 collate coll_ci_ai;

    recreate sequence g;
    recreate table test (
       id int
      ,nm_cs_as dm_name_cs_as
      ,nm_ci_ai dm_name_ci_ai
    );
	create table alphabet(
		id smallint generated by default as identity
		,s dm_name_cs_as
	);
	commit;

	insert into alphabet(s) values( 'a' );
	insert into alphabet(s) values( 'A' );
	insert into alphabet(s) values( 'b' );
	insert into alphabet(s) values( 'B' );
	insert into alphabet(s) values( 'c' );
	insert into alphabet(s) values( 'C' );
	insert into alphabet(s) values( 'd' );
	insert into alphabet(s) values( 'D' );
	insert into alphabet(s) values( 'e' );
	insert into alphabet(s) values( 'E' );
	insert into alphabet(s) values( 'f' );
	insert into alphabet(s) values( 'F' );
	insert into alphabet(s) values( 'g' );
	insert into alphabet(s) values( 'G' );
	insert into alphabet(s) values( 'h' );
	insert into alphabet(s) values( 'H' );
	insert into alphabet(s) values( 'i' );
	insert into alphabet(s) values( 'Ž' );
	insert into alphabet(s) values( 'I' );
	insert into alphabet(s) values( 'j' );
	insert into alphabet(s) values( 'J' );
	insert into alphabet(s) values( 'k' );
	insert into alphabet(s) values( 'K' );
	insert into alphabet(s) values( 'l' );
	insert into alphabet(s) values( 'L' );
	insert into alphabet(s) values( 'm' );
	insert into alphabet(s) values( 'M' );
	insert into alphabet(s) values( 'n' );
	insert into alphabet(s) values( 'N' );
	insert into alphabet(s) values( 'o' );
	insert into alphabet(s) values( 'O' );
	insert into alphabet(s) values( 'p' );
	insert into alphabet(s) values( 'P' );
	insert into alphabet(s) values( 'r' );
	insert into alphabet(s) values( 'R' );
	insert into alphabet(s) values( 's' );
	insert into alphabet(s) values( 'S' );

	insert into alphabet(s) values( 'š' );
	insert into alphabet(s) values( 'Š' );
	insert into alphabet(s) values( 'z' );
	insert into alphabet(s) values( 'Z' );
	insert into alphabet(s) values( 't' );
	insert into alphabet(s) values( 'T' );
	insert into alphabet(s) values( 'u' );
	insert into alphabet(s) values( 'U' );
	insert into alphabet(s) values( 'v' );
	insert into alphabet(s) values( 'V' );
	insert into alphabet(s) values( 'õ' );
	insert into alphabet(s) values( 'Õ' );
	insert into alphabet(s) values( 'ä' );
	insert into alphabet(s) values( 'Ä' );
	insert into alphabet(s) values( 'ž' );
	insert into alphabet(s) values( 'ö' );
	insert into alphabet(s) values( 'Ö' );
	insert into alphabet(s) values( 'ü' );
	insert into alphabet(s) values( 'Ü' );
	insert into alphabet(s) values( 'x' );
	insert into alphabet(s) values( 'X' );
	insert into alphabet(s) values( 'y' );
	insert into alphabet(s) values( 'Y' );

    insert into test(id, nm_cs_as, nm_ci_ai) select row_number()over(), s, s from alphabet order by rand();
    commit;

    select
        listagg(distinct nm_cs_as, ':') within group (order by nm_cs_as) as blob_id_cs_as
       ,listagg(distinct nm_ci_ai, ':') within group (order by nm_ci_ai) as blob_id_ci_ai
    from test;
"""

act = isql_act('db', test_script, substitutions = [('BLOB_ID.*', '')])

@pytest.mark.version('>=6.0')
def test_1(act: Action):

    expected_stdout = f"""
        a:A:ä:Ä:b:B:c:C:d:D:e:E:f:F:g:G:h:H:i:I:j:J:k:K:l:L:m:M:n:N:o:O:ö:Ö:õ:Õ:p:P:r:R:s:S:š:Š:t:T:u:U:ü:Ü:v:V:x:X:y:Y:z:Z:ž:Ž
        ä:b:c:d:e:f:g:h:i:j:k:l:m:n:ö:p:r:š:t:ü:v:x:y:ž
    """
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
