#coding:utf-8

"""
ID:          transactions.read-consist-sttm-restart-max-limit
TITLE:       READ CONSISTENCY. Maximal number of statement-level restarts must be 10.
DESCRIPTION:
  Initial article for reading:
      https://asktom.oracle.com/pls/asktom/f?p=100:11:::::P11_QUESTION_ID:11504247549852
      Note on terms which are used there: "BLOCKER", "LONG" and "FIRSTLAST" - their names are slightly changed here
      to: LOCKER-1, WORKER and LOCKER-2 respectively.

      See also: doc/README.read_consistency.md
      Letter from Vlad: 15.09.2020 20:04 // subj "read consistency // addi test(s)"

      ::: NB :::
      This test uses script %FBT_REPO%/files/read-consist-sttm-restart-DDL.sql which contains common DDL for all other such tests.
      Particularly, it contains two TRIGGERS (TLOG_WANT and TLOG_DONE) which are used for logging of planned actions and actual
      results against table TEST. These triggers use AUTONOMOUS transactions in order to have ability to see results in any
      outcome of test.

      Detailed description can be found in "read-consist-sttm-restart-on-update-04.fbt", this test is based on the same ideas:
         * initial script add records with ID = 1...12 and does commit;
         * start locker-1 which catch record with ID = 1 that is to be involved futher in cursor of worker;
         * start worker DML which must change records in descending order of ID, starting with ID=2; worker must write ID = ID * 100 for each row;
         * start locker-2 which changes record with ID=12 by assigning this ID to -12, makes COMMIT and locks this record again (makes UPDATE w/o commit);
         * locker-1 releases record with ID=1, then changes record with ID=11 by assigning this ID to -11, makes COMMIT and locks this record again;
         * locker-2 releases record with ID=-12, then changes record with ID=10 by assigning this ID to -10, makes COMMIT and locks this record again;
         * ... and so on, until number of such actions iterations less 10 or 11 (see below) ...

      Each UPDATE that is performed by lockers (starting from ID=11) produces new ID (-11, -10, -9, ...) that was not present in the scope which worker
      could see before this action. This forces worker to make statement-level restart.

      When number of such new IDs is less than 10 then worker must finish its job successfully.
      But if this number if 11 then worker must raise exception (SQLSTATE = 40001 / deadlock / update conflicts) and rollback all changes.

      Test verifies both cases, using loop with TWO iterations (see 'main_iter' below): first for 10 and second to 11 records that are to be updated.
      After each iteration we do queries to the table TEST and to the view V_WORKER_LOG which contains data generated by trigger TLOG_DONE for logging.

      Test verifies restart number for three modes of WORKER job: UPDATE, MERGE, DELETE and SELECT WITH LOCK (see loop for checked_DML: 'upd', 'mer', 'del', 'lok').
      NOTE-1.
          For 'SELECT WITH LOCK' we must provide that no rows will be returned to client while worker is waiting for records.
          EXECUTE BLOCK with for-select which does nothing is used for this.

      NOTE-2.
          SELECT WITH LOCK does not allow to use VIEW as subject of query (raises "-WITH LOCK can be used only with a single physical table").
          This error is expected in current FB versions and its text presents in expected_std* section.

      Checked on 4.0.0.2195 SS/CS.
      29.09.2020: added for-loop in order to check different target objects: TABLE ('test') and VIEW ('v_test'), see 'target_object_type'.
FBTEST:      functional.transactions.read_consist_sttm_restart_max_limit
NOTES:
[29.07.2022] pzotov
    Checked on 4.0.1.2692 (SS/SC), 5.0.0.591 (SS/SC)
"""

import subprocess
import pytest
from firebird.qa import *
from pathlib import Path
import time

substitutions = [('=', ''), ('[ \t]+', ' '), ('.*After line \\d+.*', ''), ('.*[\\-]?concurrent transaction number is \\d+', 'concurrent transaction number is'), ('.*At\\s+block\\s+line(:)?\\s+\\d+(,)?\\s+col(:)?\\s+\\d+', ''), ('.After\\s+line\\s+\\d+\\s+.*', '')]


db = db_factory()
act = python_act('db', substitutions=substitutions)

fn_worker_sql = temp_file('tmp_worker.sql')
fn_worker_log = temp_file('tmp_worker.log')
fn_worker_err = temp_file('tmp_worker.err')


expected_stdout = """
    checked_mode: table, checked_DML = upd, iter = 0, restarts number to be tested: 10
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      ID
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG: =======
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:   -1200
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:   -1100
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:   -1000
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -900
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -800
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -700
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -600
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -500
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -400
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:    -300
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:     100
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:     200
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG: ======= ====== =====================
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        1
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        2
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        2
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        3
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        3
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        4
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        4
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        5
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        5
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        6
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        6
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        7
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        7
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        8
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        8
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        9
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        9
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                       10
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                       10
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -3 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -4 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -5 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -6 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -7 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -8 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:      -9 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:     -10 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:     -11 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:     -12 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 0, worker STDLOG: Records affected: 31

    checked_mode: table, checked_DML = upd, iter = 1, restarts number to be tested: 12
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG: Records affected: 2
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      ID
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG: =======
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:     -14
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:     -13
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:     -12
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:     -11
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:     -10
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -9
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -8
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -7
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -6
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -5
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -4
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:      -3
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG: ======= ====== =====================
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        1
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        2
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        2
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        3
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        3
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        4
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        4
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        5
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        5
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        6
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        6
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        7
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        7
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        8
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        8
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        9
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        9
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                       10
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                       10
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                       11
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = upd, iter = 1, worker STDLOG: Records affected: 21
    checked_mode: table, checked_DML = upd, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: table, checked_DML = upd, iter = 1, worker STDERR: deadlock
    checked_mode: table, checked_DML = upd, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: table, checked_DML = upd, iter = 1, worker STDERR: -concurrent transaction number is 343

    checked_mode: table, checked_DML = mer, iter = 0, restarts number to be tested: 10
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      ID
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG: =======
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:   -1200
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:   -1100
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:   -1000
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -900
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -800
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -700
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -600
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -500
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -400
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:    -300
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:     100
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:     200
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG: ======= ====== =====================
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        1
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        2
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        2
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        3
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        3
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        4
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        4
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        5
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        5
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        6
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        6
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        7
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        7
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        8
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        8
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        9
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        9
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                       10
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                       10
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -3 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -4 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -5 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -6 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -7 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -8 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:      -9 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:     -10 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:     -11 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:     -12 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 0, worker STDLOG: Records affected: 31

    checked_mode: table, checked_DML = mer, iter = 1, restarts number to be tested: 12
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG: Records affected: 2
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      ID
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG: =======
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:     -14
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:     -13
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:     -12
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:     -11
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:     -10
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -9
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -8
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -7
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -6
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -5
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -4
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:      -3
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG: ======= ====== =====================
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        1
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        2
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        2
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        3
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        3
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        4
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        4
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        5
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        5
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        6
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        6
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        7
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        7
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        8
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        8
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        9
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        9
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                       10
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                       10
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                       11
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = mer, iter = 1, worker STDLOG: Records affected: 21
    checked_mode: table, checked_DML = mer, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: table, checked_DML = mer, iter = 1, worker STDERR: deadlock
    checked_mode: table, checked_DML = mer, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: table, checked_DML = mer, iter = 1, worker STDERR: -concurrent transaction number is 696

    checked_mode: table, checked_DML = del, iter = 0, restarts number to be tested: 10
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG: Records affected: 0
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG: ======= ====== =====================
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        1
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        2
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        2
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        3
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        3
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        4
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        4
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        5
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        5
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        6
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        6
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        7
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        7
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        8
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        8
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        9
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        9
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                       10
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                       10
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -3 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -4 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -5 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -6 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -7 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -8 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:      -9 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:     -10 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:     -11 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:     -12 DEL                       11
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = del, iter = 0, worker STDLOG: Records affected: 31

    checked_mode: table, checked_DML = del, iter = 1, restarts number to be tested: 12
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG: Records affected: 2
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      ID
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG: =======
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:     -14
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:     -13
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:     -12
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:     -11
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:     -10
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -9
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -8
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -7
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -6
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -5
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -4
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:      -3
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG: ======= ====== =====================
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        1
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        2
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        2
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        3
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        3
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        4
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        4
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        5
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        5
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        6
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        6
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        7
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        7
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        8
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        8
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        9
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        9
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                       10
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                       10
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                       11
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                       11
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = del, iter = 1, worker STDLOG: Records affected: 21
    checked_mode: table, checked_DML = del, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: table, checked_DML = del, iter = 1, worker STDERR: deadlock
    checked_mode: table, checked_DML = del, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: table, checked_DML = del, iter = 1, worker STDERR: -concurrent transaction number is 1049

    checked_mode: table, checked_DML = lok, iter = 0, restarts number to be tested: 10
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      ID
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG: =======
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:     -12
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:     -11
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:     -10
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -9
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -8
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -7
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -6
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -5
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -4
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:      -3
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:       1
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:       2
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG:
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: table, checked_DML = lok, iter = 0, worker STDLOG: Records affected: 0

    checked_mode: table, checked_DML = lok, iter = 1, restarts number to be tested: 12
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      ID
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG: =======
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:     -14
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:     -13
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:     -12
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:     -11
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:     -10
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -9
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -8
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -7
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -6
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -5
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -4
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:      -3
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:       1
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:       2
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG:
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: table, checked_DML = lok, iter = 1, worker STDLOG: Records affected: 0
    checked_mode: table, checked_DML = lok, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: table, checked_DML = lok, iter = 1, worker STDERR: deadlock
    checked_mode: table, checked_DML = lok, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: table, checked_DML = lok, iter = 1, worker STDERR: -concurrent transaction number is 1282
    checked_mode: table, checked_DML = lok, iter = 1, worker STDERR: -At block line: 1, col: 39

    checked_mode: view, checked_DML = upd, iter = 0, restarts number to be tested: 10
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      ID
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG: =======
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:   -1200
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:   -1100
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:   -1000
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -900
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -800
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -700
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -600
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -500
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -400
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:    -300
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:     100
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:     200
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG: ======= ====== =====================
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        1
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        2
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        2
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        3
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        3
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        4
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        4
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        5
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        5
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        6
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        6
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        7
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        7
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        8
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        8
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                        9
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                        9
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                       10
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                       10
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       2 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:       1 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -3 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -4 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -5 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -6 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -7 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -8 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:      -9 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:     -10 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:     -11 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:     -12 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 0, worker STDLOG: Records affected: 31

    checked_mode: view, checked_DML = upd, iter = 1, restarts number to be tested: 12
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG: Records affected: 2
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      ID
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG: =======
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:     -14
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:     -13
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:     -12
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:     -11
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:     -10
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -9
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -8
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -7
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -6
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -5
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -4
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:      -3
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG: ======= ====== =====================
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        1
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        2
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        2
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        3
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        3
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        4
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        4
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        5
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        5
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        6
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        6
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        7
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        7
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        8
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        8
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                        9
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                        9
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                       10
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                       10
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       2 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:       1 UPD                       11
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = upd, iter = 1, worker STDLOG: Records affected: 21
    checked_mode: view, checked_DML = upd, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: view, checked_DML = upd, iter = 1, worker STDERR: deadlock
    checked_mode: view, checked_DML = upd, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: view, checked_DML = upd, iter = 1, worker STDERR: -concurrent transaction number is 1630

    checked_mode: view, checked_DML = mer, iter = 0, restarts number to be tested: 10
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      ID
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG: =======
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:   -1200
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:   -1100
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:   -1000
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -900
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -800
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -700
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -600
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -500
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -400
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:    -300
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:     100
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:     200
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG: ======= ====== =====================
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        1
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        2
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        2
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        3
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        3
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        4
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        4
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        5
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        5
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        6
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        6
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        7
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        7
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        8
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        8
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                        9
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                        9
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                       10
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                       10
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       2 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:       1 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -3 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -4 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -5 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -6 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -7 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -8 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:      -9 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:     -10 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:     -11 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:     -12 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 0, worker STDLOG: Records affected: 31

    checked_mode: view, checked_DML = mer, iter = 1, restarts number to be tested: 12
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG: Records affected: 2
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      ID
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG: =======
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:     -14
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:     -13
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:     -12
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:     -11
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:     -10
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -9
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -8
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -7
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -6
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -5
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -4
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:      -3
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG: ======= ====== =====================
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        1
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        2
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        2
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        3
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        3
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        4
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        4
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        5
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        5
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        6
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        6
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        7
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        7
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        8
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        8
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                        9
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                        9
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                       10
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                       10
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       2 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:       1 UPD                       11
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = mer, iter = 1, worker STDLOG: Records affected: 21
    checked_mode: view, checked_DML = mer, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: view, checked_DML = mer, iter = 1, worker STDERR: deadlock
    checked_mode: view, checked_DML = mer, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: view, checked_DML = mer, iter = 1, worker STDERR: -concurrent transaction number is 1983

    checked_mode: view, checked_DML = del, iter = 0, restarts number to be tested: 10
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG: Records affected: 0
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG: ======= ====== =====================
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        1
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        2
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        2
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        3
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        3
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        4
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        4
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        5
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        5
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        6
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        6
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        7
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        7
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        8
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        8
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                        9
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                        9
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                       10
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                       10
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       2 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:       1 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -3 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -4 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -5 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -6 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -7 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -8 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:      -9 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:     -10 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:     -11 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:     -12 DEL                       11
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = del, iter = 0, worker STDLOG: Records affected: 31

    checked_mode: view, checked_DML = del, iter = 1, restarts number to be tested: 12
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG: Records affected: 2
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      ID
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG: =======
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:     -14
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:     -13
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:     -12
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:     -11
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:     -10
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -9
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -8
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -7
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -6
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -5
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -4
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:      -3
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:  OLD_ID OP              SNAP_NO_RANK
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG: ======= ====== =====================
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        1
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        2
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        2
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        3
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        3
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        4
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        4
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        5
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        5
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        6
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        6
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        7
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        7
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        8
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        8
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                        9
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                        9
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                       10
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                       10
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       2 DEL                       11
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:       1 DEL                       11
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = del, iter = 1, worker STDLOG: Records affected: 21
    checked_mode: view, checked_DML = del, iter = 1, worker STDERR: Statement failed, SQLSTATE = 40001
    checked_mode: view, checked_DML = del, iter = 1, worker STDERR: deadlock
    checked_mode: view, checked_DML = del, iter = 1, worker STDERR: -update conflicts with concurrent update
    checked_mode: view, checked_DML = del, iter = 1, worker STDERR: -concurrent transaction number is 2336

    checked_mode: view, checked_DML = lok, iter = 0, restarts number to be tested: 10
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:      ID
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG: =======
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       1
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       2
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       3
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       4
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       5
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       6
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       7
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       8
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:       9
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:      10
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:      11
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:      12
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG:
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG: Records affected: 12
    checked_mode: view, checked_DML = lok, iter = 0, worker STDLOG: Records affected: 0
    checked_mode: view, checked_DML = lok, iter = 0, worker STDERR: Statement failed, SQLSTATE = 42000
    checked_mode: view, checked_DML = lok, iter = 0, worker STDERR: Dynamic SQL Error
    checked_mode: view, checked_DML = lok, iter = 0, worker STDERR: -SQL error code = -104
    checked_mode: view, checked_DML = lok, iter = 0, worker STDERR: -WITH LOCK can be used only with a single physical table

    checked_mode: view, checked_DML = lok, iter = 1, restarts number to be tested: 12
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:      ID
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG: =======
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       1
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       2
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       3
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       4
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       5
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       6
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       7
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       8
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:       9
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:      10
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:      11
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:      12
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:      13
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:      14
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG:
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG: Records affected: 14
    checked_mode: view, checked_DML = lok, iter = 1, worker STDLOG: Records affected: 0
    checked_mode: view, checked_DML = lok, iter = 1, worker STDERR: Statement failed, SQLSTATE = 42000
    checked_mode: view, checked_DML = lok, iter = 1, worker STDERR: Dynamic SQL Error
    checked_mode: view, checked_DML = lok, iter = 1, worker STDERR: -SQL error code = -104
    checked_mode: view, checked_DML = lok, iter = 1, worker STDERR: -WITH LOCK can be used only with a single physical table

"""

@pytest.mark.version('>=4.0')
def test_1(act: Action, fn_worker_sql: Path, fn_worker_log: Path, fn_worker_err: Path, capsys):

    sql_init = (act.files_dir / 'read-consist-sttm-restart-DDL.sql').read_text()

    for checked_mode in('table', 'view'):
        target_obj = 'test' if checked_mode == 'table' else 'v_test'

        for checked_DML in('upd', 'mer', 'del', 'lok'):
            worker_dml = "select 'UNKNOWN MODE' as msg from rdb$database"
            if checked_DML == 'upd':
                worker_dml = f'update {target_obj} set id = id * 100 where id <= 2 order by id DESC;'
            elif checked_DML == 'mer':
                worker_dml = f'merge into {target_obj} t using (select x.id from {target_obj} x where x.id <= 2 order by id DESC) s on t.id = s.id when matched then update set t.id = s.id * 100;'
            elif checked_DML == 'del':
                worker_dml = f'delete from {target_obj} where id <= 2 order by id DESC;'
            elif checked_DML == 'lok':
                # ::: NB :::
                # We must SUPRESS sending record to client for SELECT WITH LOCK, otherwise error
                # deadlock/update conflist will raise immediately! Because of this, we  enclose
                # such select into execute block which returns nothing:
                worker_dml = f'set term ^; execute block as declare c int; begin for select id from {target_obj} where id<=2 order by id desc with lock into c do begin end end^ set term ;^'

            for main_iter in (0,1):

                ###################################################################################
                ###  H O W    M A N Y    R E S T A R T S    W E    W A N T    T O    C H E C K  ###
                ###################################################################################
                ROWS_TO_ADD = 10 + 2 * main_iter

                sql_addi = f'''
                    set term ^;
                    execute block as
                    begin
                        rdb$set_context('USER_SESSION', 'WHO', 'INIT_DATA');
                    end
                    ^
                    set term ;^
                    insert into {target_obj}(id, x) select row_number()over(),row_number()over() from rdb$types rows (2 + {ROWS_TO_ADD}); -- <<< INITIAL DATA
                    commit;
                '''

                act.isql(switches=['-q'], input = ''.join( (sql_init, sql_addi) ) )

                with act.db.connect() as con_lock_1, act.db.connect() as con_lock_2:
                    for i,c in enumerate((con_lock_1,con_lock_2)):
                        sttm = f"execute block as begin rdb$set_context('USER_SESSION', 'WHO', 'LOCKER #{i+1}'); end"
                        c.execute_immediate(sttm)

                    #########################
                    ###  L O C K E R - 1  ###
                    #########################

                    con_lock_1.execute_immediate( f'update {target_obj} set id=id where id = 1' )

                    worker_sql = f'''
                        set list on;
                        set autoddl off;
                        set term ^;
                        execute block as
                        begin
                            rdb$set_context('USER_SESSION','WHO', 'WORKER');
                        end
                        ^
                        set term ;^
                        commit;
                        SET KEEP_TRAN_PARAMS ON;
                        set transaction read committed read consistency;
                        set list off;
                        set wng off;

                        set count on;

                        -- Run UPDATE | DELETE | MERGE | SELECT WITH LOCK.
                        -- EVery statement ends with 'ORDER BY ID DESC' and must hang because of lockes:
                        {worker_dml} 

                        -- check results:
                        -- ###############

                        select id from {target_obj} order by id;

                        select v.old_id, v.op, v.snap_no_rank
                        from v_worker_log v
                        where v.op = iif( '{checked_DML}' = 'mer', 'upd', '{checked_DML}'); -- 'UPD' or 'DEL'; for 'SELECT WITH LOCK' no records will be in v_worker_log.


                        --set width who 10;
                        -- DO NOT check this! Values can differ here from one run to another!
                        -- select id, trn, who, old_id, new_id, op, rec_vers, global_cn, snap_no from tlog_done order by id;
                        rollback;

                    '''

                    fn_worker_sql.write_text(worker_sql)

                    with fn_worker_log.open(mode='w') as hang_out, fn_worker_err.open(mode='w') as hang_err:

                        ############################################################################
                        ###  L A U N C H     W O R K E R    U S I N G     I S Q L,   A S Y N C.  ###
                        ############################################################################
                        p_worker = subprocess.Popen([act.vars['isql'], '-i', str(fn_worker_sql),
                                                       '-user', act.db.user,
                                                       '-password', act.db.password,
                                                       '-pag', '999999',
                                                       act.db.dsn
                                                    ],
                                                      stdout = hang_out,
                                                      stderr = hang_err
                                                   )
                        time.sleep(1)

                        cur_lock_1 = con_lock_1.cursor()
                        cur_lock_2 = con_lock_2.cursor()
                        sttm = f'update {target_obj} set id = ? where abs( id ) = ?'


                        for i in range(0,ROWS_TO_ADD):
                            v_id = 2 + ROWS_TO_ADD-i
                            if i % 2 == 0:
                                cur_lock_2.execute( sttm, ( -abs( v_id ), v_id, ) )
                                con_lock_2.commit()
                                cur_lock_2.execute( sttm, ( -abs( v_id ), v_id, ) )
                                con_lock_1.commit()
                            else:
                                cur_lock_1.execute( sttm, ( -abs( v_id ), v_id, ) )
                                con_lock_1.commit()
                                cur_lock_1.execute( sttm, ( -abs( v_id ), v_id, ) )
                                con_lock_2.commit()

                        if ROWS_TO_ADD % 2 == 0:
                            if con_lock_2.is_active():
                                con_lock_2.commit()
                            con_lock_1.commit()
                        else:
                            if con_lock_1.is_active():
                                con_lock_1.commit()
                            con_lock_2.commit()


                        # Here we wait for ISQL complete its mission:
                        p_worker.wait()

                #< with ... con_lock_1, ... con_lock_2

                # CHECK RESULTS
                ###############
                print( f'checked_mode: {checked_mode}, checked_DML = {checked_DML}, iter = {main_iter}, restarts number to be tested: {ROWS_TO_ADD}' )

                for g in (fn_worker_log, fn_worker_err):
                    logname = 'STDLOG' if g == fn_worker_log else 'STDERR'
                    with g.open() as f:
                        for line in f:
                            if line:
                                print( f'checked_mode: {checked_mode}, checked_DML = {checked_DML}, iter = {main_iter}, worker {logname}: {line}'  )

            #< for main_iter in (0,1)
        # < for checked_DML in ('upd', 'mer', 'del', 'lok')
    # < for checked_mode in ('table', 'view')

    act.expected_stdout = expected_stdout
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
