#coding:utf-8
"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/9155
TITLE:       gbak FAST_PATH: perf smoke on 300k rows with 2 parallel workers
DESCRIPTION:
    [text generated by zcode.ai]
    Smoke-level performance comparison of normal vs FAST_PATH backup/restore on a
    data-heavy table (300k rows, ~25 MB) with the parallel worker count fixed to 2.
    Marked `perf_measure`: results depend on machine load, so the test
      * REQUIRES both modes to produce identical data;
      * PRINTS elapsed times and speed-up ratios for manual analysis;
      * only asserts a loose anti-regression guard: FAST_PATH total time must not be
        more than 2x the normal total (README reports ~2x speed-up; a strict perf gate
        belongs to a dedicated suite on a quiet machine).
NOTES:
    [30.09.2026] zcode.ai
    Initial code, description and comments were generated by zcode.ai.
    Checked on 6.0.0.2190.
"""
import time
from pathlib import Path

import pytest
from firebird.qa import *

try:
    # leaf folder is a package inside the main firebird-qa tree (has __init__.py)
    from . import fp_helpers as fp
except ImportError:
    # loose folder without __init__.py, e.g. qa\zcode\probe01
    import fp_helpers as fp

ROW_COUNT = 300_000

db = db_factory(charset='UTF8')
act = python_act('db')

db_res = db_factory(filename='fp06_restored.fdb', charset='UTF8')
act_res = python_act('db_res')

tmp_fbk = temp_file('fp06_backup.fbk')

DDL = f"""
    create table t_big (id integer primary key, val bigint, txt varchar(120));
    -- generate_series() is used for the initial fill: it takes seconds, unlike
    -- 'select first <N> from <cross join>' where the engine produces the whole
    -- join before FIRST is applied (measured 165s vs 5.6s for 300k rows on the
    -- target host), and unlike a deep recursive CTE which hits
    -- 'too many concurrent executions of the same request'.
    insert into t_big (id, val, txt)
    with
    a as (
        select i, mod(i, 255) as j
        from generate_series(1, {ROW_COUNT}) as s(i)
    ),
    b as (
        select i, j, cast(j * 100000 + j * 100 + j as bigint) as k
        from a
    )
    select i, j, lpad('', 100, 'x') || k
    from b;
    commit;
"""

STATS_QUERY = "select count(*), min(val), max(val), min(txt), max(txt) from t_big"


@pytest.mark.ai
@pytest.mark.perf_measure
@pytest.mark.version('>=6.0')
#def test_fast_path_perf_smoke(act: Action, act_res: Action, tmp_fbk: Path):
def test_1(act: Action, act_res: Action, tmp_fbk: Path):
    t0 = time.perf_counter()
    act.isql(switches=['-q'], input=DDL, combine_output=True)
    assert act.stdout == '', act.stdout
    act.reset()
    print(f"\nload {ROW_COUNT} rows: {time.perf_counter() - t0:.2f}s")

    src_stats = fp.fetch_rows(act, STATS_QUERY)
    assert src_stats[0][0] == ROW_COUNT

    timings = {}
    # backup normal / fast
    for mode in ('normal', 'fast'):
        t0 = time.perf_counter()
        fp.gbak_backup(act, Path(act.db.db_path), tmp_fbk, fast=(mode == 'fast'))
        timings[f'backup_{mode}'] = time.perf_counter() - t0

    # restore normal / fast (same backup file is used for both modes)
    for mode in ('normal', 'fast'):
        t0 = time.perf_counter()
        fp.gbak_restore(act, tmp_fbk, Path(act_res.db.db_path), fast=(mode == 'fast'))
        timings[f'restore_{mode}'] = time.perf_counter() - t0
        assert fp.fetch_rows_from(act_res, STATS_QUERY) == src_stats, \
            f"{mode} restore changed the data"

    b_norm = timings['backup_normal']
    b_fast = timings['backup_fast']
    r_norm = timings['restore_normal']
    r_fast = timings['restore_fast']
    total_norm = b_norm + r_norm
    total_fast = b_fast + r_fast

    print(f"\nparallel workers = {fp.PARALLEL_WORKERS}, rows = {ROW_COUNT}")
    print(f"backup : normal {b_norm:8.3f}s | fast {b_fast:8.3f}s | speed-up {b_norm / b_fast:5.2f}x")
    print(f"restore: normal {r_norm:8.3f}s | fast {r_fast:8.3f}s | speed-up {r_norm / r_fast:5.2f}x")
    print(f"total  : normal {total_norm:8.3f}s | fast {total_fast:8.3f}s | "
          f"speed-up {total_norm / total_fast:5.2f}x")

    # loose anti-regression guard only - see the docstring
    assert total_fast < total_norm * 2, \
        f"FAST_PATH more than 2x slower than normal mode: {timings}"
