#coding:utf-8
"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/9155
TITLE:       gbak FAST_PATH: 4-way backup/restore matrix keeps data and metadata identical
DESCRIPTION:
    [text generated by zcode.ai]
    Builds the table t_rich defined by the RICH_DDL constant from fp_helpers.py:
    that DDL covers all datatypes supported by Firebird - every type is present
    twice, as a directly declared column and as a column based on a domain -
    and fills it by the RICH_ROWS constant with boundary, NULL and moderate rows.
    Then runs the full combination matrix:
        backup {normal, -fast_path}  x  restore {normal, -fast_path}
    All operations go through the Services Manager with 2 parallel workers.
    For every combination we assert:
      * gbak exits successfully with no warnings;
      * restored data is identical to the source (row-by-row, blobs included);
      * `gfix -v -full` is silent on the restored database;
      * restored metadata equals the source metadata (isql -x extract diff is empty).
NOTES:
    [30.09.2026] zcode.ai
    Initial code, description and comments were generated by zcode.ai.
    Checked on 6.0.0.2190.
"""
from pathlib import Path

import pytest
from firebird.qa import *

try:
    # leaf folder is a package inside the main firebird-qa tree (has __init__.py)
    from . import fp_helpers as fp
except ImportError:
    # loose folder without __init__.py, e.g. qa\zcode\probe01
    import fp_helpers as fp

db = db_factory(charset='UTF8')
act = python_act('db')

db_res = db_factory(filename='fp01_restored.fdb', charset='UTF8')
act_res = python_act('db_res')

tmp_fbk = temp_file('fp01_matrix_backup.fbk')


def meta_without_create(act: Action) -> str:
    """Metadata extract without the CREATE DATABASE line (file name differs)."""
    meta = act.extract_meta(charset='utf8', io_enc='utf8')
    act.reset()
    return '\n'.join(x for x in meta.splitlines() if 'CREATE DATABASE' not in x)


@pytest.mark.ai
@pytest.mark.version('>=6.0')
def test_1(act: Action, act_res: Action, tmp_fbk: Path, capsys):
    act.isql(switches=['-q'], input=fp.RICH_DDL + fp.RICH_ROWS, combine_output=True)
    assert act.stdout == '', act.stdout
    act.reset()

    src_rows = fp.fetch_rows(act, fp.RICH_QUERY)
    assert len(src_rows) == 3
    src_meta = meta_without_create(act)

    for backup_fast in (False, True):
        fp.gbak_backup(act, Path(act.db.db_path), tmp_fbk, fast=backup_fast)

        for restore_fast in (False, True):
            tag = f"backup={'FAST' if backup_fast else 'NORM'} restore={'FAST' if restore_fast else 'NORM'}"
            fp.gbak_restore(act, tmp_fbk, Path(act_res.db.db_path), fast=restore_fast)

            res_rows = fp.fetch_rows_from(act_res, fp.RICH_QUERY)
            assert res_rows == src_rows, f"{tag}: restored data differs"

            fp.validated_clean(act_res, Path(act_res.db.db_path))

            res_meta = meta_without_create(act_res)
            assert res_meta == src_meta, f"{tag}: metadata differs after restore"

    act.expected_stdout = ''
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
