#coding:utf-8
"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/8564
TITLE:        Non-decimal integer literals (SQL:2023 T661), part 3: binary
DESCRIPTION:
    [text generated by zcode.ai]
    Covers binary-literal cases of doc/sql.extensions/README.decimal_and_non_decimal_literals.txt:
    * case insensitivity of prefix (0b11010100 = 0B11010100 = 212); 0b0000000 => 0;
    * value-based typing boundaries (types are checked in non_dec_int_resulting_types_test.py):
        31 ones                          -> 2147483647        (max INTEGER)
        1 + 31 zeroes                    -> 2147483648        (min BIGINT, positive)
        63 ones                          -> 9223372036854775807
        1 + 63 zeroes                    -> 9223372036854775808
        127 ones                         -> max INT128 = 170141183460469231731687303715884105727
    * negative values via unary minus (-0b11010100 => -212, -0b<127 ones> => -max INT128);
    * value 2**127 (1 followed by 127 zeroes) raises error 'Overflow of the number'.
NOTES:
    [05.10.2026] pzotov
    Test was generated by zcode.ai.
    Commit: afba27964f368892b02f582b8ea68c512b7541ad.
    See also: doc/sql.extensions/README.decimal_and_non_decimal_literals.txt
    Checked on 6.0.0.2197-1e316df.
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    set bail off;
    select 0b11010100 v1, 0B11010100 v2, 0b0000000 v3, 0b1 v4, -0b11010100 v5 from rdb$database;
    select 0b1111111111111111111111111111111 v1, 0b10000000000000000000000000000000 v2 from rdb$database;
    select 0b111111111111111111111111111111111111111111111111111111111111111 v1, 0b1000000000000000000000000000000000000000000000000000000000000000 v2 from rdb$database;
    select 0b1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 vmax from rdb$database;
    select -0b1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 vmin from rdb$database;
    select 0b10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 err1 from rdb$database;
"""

substitutions = [('-Token unknown.*', '-Token unknown'),
                 ('At line.*', ''),
                 ('After line.*', ''),
                 ('[ \t]+', ' ')]

act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    V1 212
    V2 212
    V3 0
    V4 1
    V5 -212
    V1 2147483647
    V2 2147483648
    V1 9223372036854775807
    V2 9223372036854775808
    VMAX 170141183460469231731687303715884105727
    VMIN -170141183460469231731687303715884105727
"""

expected_stderr = """
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -Overflow of the number
"""

@pytest.mark.version('>=6.0')
@pytest.mark.ai
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.expected_stderr = expected_stderr
    act.execute()
    assert (act.clean_stdout == act.clean_expected_stdout and
            act.clean_stderr == act.clean_expected_stderr)
