#coding:utf-8
"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/8564
TITLE:        Non-decimal literals and underscores: numeric literal glued to identifier now raises error
DESCRIPTION:
    [text generated by zcode.ai]
    PR #8564 changed the lexer, and as side effect a numeric literal GLUED to identifier now raises error.
    Per PR description, following statements that were parsed before (numeric literal silently split from following
    letters) now raise 'Token unknown':
        select * from rdb$database where rdb$relation_id>1and 1=2;        -- token '1a'
        select substring(r.rdb$character_set_name from 1for 2) ...;       -- token '1f'
        select 1,2,3 from rdb$database where 1=0order by 1;               -- token '0or'
    The same statements with proper whitespace work as before, which is checked here too.
NOTES:
    [05.10.2026] pzotov
    Test was generated by zcode.ai.
    Commit: afba27964f368892b02f582b8ea68c512b7541ad.
    See also: doc/sql.extensions/README.decimal_and_non_decimal_literals.txt
    Checked on 6.0.0.2197-1e316df.
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    set bail off;
    -- with proper whitespace everything works:
    select count(*) c1 from rdb$database where rdb$relation_id > 1 and 1 = 2;
    select substring('abcdef' from 1 for 2) c2 from rdb$database;
    select count(*) c3 from rdb$database where 1 = 0 order by 1;
    -- since 6.0 numeric literal glued to identifier raises error (see PR #8564):
    select * from rdb$database where rdb$relation_id>1and 1=2;
    select substring('abcdef' from 1for 2) from rdb$database;
    select 1,2,3 from rdb$database where 1=0order by 1;
"""

substitutions = [('-Token unknown.*', '-Token unknown'),
                 ('At line.*', ''),
                 ('After line.*', ''),
                 ('[ \t]+', ' ')]

act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    C1 0
    C2 ab
    C3 0
"""

expected_stderr = """
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1a
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1f
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -0or
"""

@pytest.mark.version('>=6.0')
@pytest.mark.ai
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.expected_stderr = expected_stderr
    act.execute()
    assert (act.clean_stdout == act.clean_expected_stdout and
            act.clean_stderr == act.clean_expected_stderr)
