#coding:utf-8
"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/8564
TITLE:        Non-decimal integer literals: no non-decimal literals in mantissa of approximate literals
DESCRIPTION:
    [text generated by zcode.ai]
    Per note 1 of doc/sql.extensions/README.decimal_and_non_decimal_literals.txt:
    "The standard allows non-decimal literals in the mantissa of an exponential number entry. For example (0xAAAe10),
    but there may be a conflict (0xEEE10). Therefore, non-decimal literals are not allowed in the mantissa (see
    <mantissa> above): 0xAAAe10 is the hexadecimal integer 0xAAAE10 = 11185680."
    Checked here:
    * 0xAAAe10 = 0xAAAE10 = 11185680 (letter 'e' is consumed as hexit, NOT as exponent marker);
    * other hex literals with 'e' inside: 0x1e2 => 482, 0xE1 => 225, 0xAbCdEf => 11259375, 0x10e2e10 => 17706512;
    * for comparison, decimal approximate literal 1.0e10 works as usual;
    * letter 'e' after binary/octal digits produces INVALID token (it is neither octal nor binary digit), e.g. '0b1e10',
      '0o17e3', '0b1_0_1e1' raise 'Token unknown' with token text '0b1e' / '0o17e' / '0b1_0_1e'.
NOTES:
    [05.10.2026] pzotov
    Test was generated by zcode.ai.
    Commit: afba27964f368892b02f582b8ea68c512b7541ad.
    See also: doc/sql.extensions/README.decimal_and_non_decimal_literals.txt
    Checked on 6.0.0.2197-1e316df.
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    set bail off;
    -- 'e' is a hexit: non-decimal literals are NOT allowed in mantissa of approximate literals:
    select 0xAAAe10 v1, 0xAAAE10 v2 from rdb$database;
    select 0x1e2 v1, 0xE1 v2, 0xAbCdEf v3, 0x10e2e10 v4 from rdb$database;
    -- for comparison, decimal approximate literal works as usual:
    select 1.0e10 v1 from rdb$database;
    -- 'e' after binary/octal digits makes invalid token:
    select 0b1e10 err1 from rdb$database;
    select 0o17e3 err2 from rdb$database;
    select 0b1_0_1e1 err3 from rdb$database;
"""

substitutions = [('-Token unknown.*', '-Token unknown'),
                 ('At line.*', ''),
                 ('After line.*', ''),
                 ('[ \t]+', ' ')]

act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    V1 11185680
    V2 11185680
    V1 482
    V2 225
    V3 11259375
    V4 17706512
    V1 10000000000.00000
"""

expected_stderr = """
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -0b1e
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -0o17e
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -0b1_0_1e
"""

@pytest.mark.version('>=6.0')
@pytest.mark.ai
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.expected_stderr = expected_stderr
    act.execute()
    assert (act.clean_stdout == act.clean_expected_stdout and
            act.clean_stderr == act.clean_expected_stderr)
