#coding:utf-8
"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/8564
TITLE:        Non-decimal integer literals (SQL:2023 T661), part 2: octal
DESCRIPTION:
    [text generated by zcode.ai]
    Covers octal-literal cases of doc/sql.extensions/README.decimal_and_non_decimal_literals.txt:
    * case insensitivity of prefix (0o12345670 = 0O12345670 = 2739128); 0o00000000 => 0;
    * value-based typing boundaries (types are checked in non_dec_int_resulting_types_test.py):
        0o17777777777  (1 + ten 7s)            -> 2147483647        (max INTEGER)
        0o20000000000  (2 + ten 0s)            -> 2147483648        (min BIGINT, positive)
        0o777777777777777777777 (21 sevens)    -> 9223372036854775807
        0o1000000000000000000000 (1 + 21 0s)   -> 9223372036854775808
        0o1 + 42 sevens                        -> max INT128 = 170141183460469231731687303715884105727
    * negative values via unary minus (-0o1 => -1, -0o1000000000000000000000 => -9223372036854775808);
    * value 2**127 (0o2 followed by 42 zeroes) raises error 'Overflow of the number'.
NOTES:
    [05.10.2026] pzotov
    Test was generated by zcode.ai.
    Commit: afba27964f368892b02f582b8ea68c512b7541ad.
    See also: doc/sql.extensions/README.decimal_and_non_decimal_literals.txt
    Checked on 6.0.0.2197-1e316df.
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    set bail off;
    select 0o12345670 v1, 0O12345670 v2, 0o00000000 v3, 0o7 v4, -0o12345670 v5, -0o1 v6 from rdb$database;
    select 0o17777777777 v1, 0o20000000000 v2 from rdb$database;
    select 0o777777777777777777777 v1, 0o1000000000000000000000 v2 from rdb$database;
    select 0o1777777777777777777777777777777777777777777 vmax from rdb$database;
    select -0o17777777777 v1, -0o1000000000000000000000 v2 from rdb$database;
    select 0o2000000000000000000000000000000000000000000 err1 from rdb$database;
"""

substitutions = [('-Token unknown.*', '-Token unknown'),
                 ('At line.*', ''),
                 ('After line.*', ''),
                 ('[ \t]+', ' ')]

act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    V1 2739128
    V2 2739128
    V3 0
    V4 7
    V5 -2739128
    V6 -1
    V1 2147483647
    V2 2147483648
    V1 9223372036854775807
    V2 9223372036854775808
    VMAX 170141183460469231731687303715884105727
    V1 -2147483647
    V2 -9223372036854775808
"""

expected_stderr = """
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -Overflow of the number
"""

@pytest.mark.version('>=6.0')
@pytest.mark.ai
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.expected_stderr = expected_stderr
    act.execute()
    assert (act.clean_stdout == act.clean_expected_stdout and
            act.clean_stderr == act.clean_expected_stderr)
