#coding:utf-8
"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/8564
TITLE:        Non-decimal integer literals: transparent conversion to SMALLINT on assignment
DESCRIPTION:
    [text generated by zcode.ai]
    Per note 4 of doc/sql.extensions/README.decimal_and_non_decimal_literals.txt:
    "There is no non-decimal literal of type SMALLINT: even 0x1 evaluates to INTEGER. However, a value within the
    range 0x0000 (decimal zero) to 0x7FFF (decimal 32767) is converted to SMALLINT transparently when it is assigned
    to a SMALLINT column, variable or parameter."
    Checked here for all three literal kinds:
    * insert into SMALLINT column of 0x7FFF / 0o77777 / 0b111111111111111 (all = 32767) works;
    * insert of values above SMALLINT range (0x8000, 0o200000, 0b1000000000000000 - all = 32768) raises SQLSTATE =
      22003 'numeric value is out of range';
    * the same for PSQL local variables (execute block with 'returns (v smallint)'):
      v = 0x7FFF / 0o77777 / 0b111111111111111 => 32767, v = -0x1 => -1.
    Type of the literals themselves (INTEGER, not SMALLINT) is verified in non_dec_int_resulting_types_test.py.
NOTES:
    [05.10.2026] pzotov
    Test was generated by zcode.ai.
    NB: 'set term' is required for execute block statements when script is fed to isql.
    Commit: afba27964f368892b02f582b8ea68c512b7541ad.
    See also: doc/sql.extensions/README.decimal_and_non_decimal_literals.txt
    Checked on 6.0.0.2197-1e316df.
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    set bail off;
    recreate table test(f smallint);
    insert into test values (0x7FFF);
    insert into test values (0o77777);
    insert into test values (0b111111111111111);
    select count(*) cnt, max(f) mx, min(f) mn from test;
    -- values above smallint range can not be assigned:
    insert into test values (0x8000);
    insert into test values (0o200000);
    insert into test values (0b1000000000000000);
    -- the same for PSQL variables:
    set term ^;
    execute block returns (v smallint) as begin v = 0x7FFF; suspend; end^
    execute block returns (v smallint) as begin v = -0x1; suspend; end^
    execute block returns (v smallint) as begin v = 0o77777; suspend; end^
    execute block returns (v smallint) as begin v = 0b111111111111111; suspend; end^
    set term ;^
"""

substitutions = [('At line.*', ''),
                 ('After line.*', ''),
                 ('[ \t]+', ' ')]

act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    CNT 3
    MX 32767
    MN 32767
    V 32767
    V -1
    V 32767
    V 32767
"""

expected_stderr = """
    Statement failed, SQLSTATE = 22003
    arithmetic exception, numeric overflow, or string truncation
    -numeric value is out of range
    Statement failed, SQLSTATE = 22003
    arithmetic exception, numeric overflow, or string truncation
    -numeric value is out of range
    Statement failed, SQLSTATE = 22003
    arithmetic exception, numeric overflow, or string truncation
    -numeric value is out of range
"""

@pytest.mark.version('>=6.0')
@pytest.mark.ai
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.expected_stderr = expected_stderr
    act.execute()
    assert (act.clean_stdout == act.clean_expected_stdout and
            act.clean_stderr == act.clean_expected_stderr)
