#coding:utf-8
"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/8564
TITLE:        Underscores in numeric literals (SQL:2023 T662), part 2: decimal literals
DESCRIPTION:
    [text generated by zcode.ai]
    Covers "Limitations for decimal literals" of doc/sql.extensions/README.decimal_and_non_decimal_literals.txt.
    Permitted (underscore between digits, including exponent digits):
        10_10 => 1010; 1_234_567_890 => 1234567890; 1234567_890 => 1234567890; 10_10.10_10 => 1010.1010; 1_000.5 =>
        1000.5; 1_23_45.6_78_09 => 12345.67809; .5_5 and 0.5_5 => 0.55; 10.10E-10_0 => 1.01E-99; -1_2_3_4_5.6E-1_0 =>
        -1.23456E-6; 12_345_678_901_234_567_890 => 12345678901234567890 (INT128).
    Forbidden (all raise 'Token unknown' with offending token shown):
        - underscore before the first character: _1010 (token '_1'), _1;
        - underscore after the last character: 100_, 1__;
        - two or more consecutive underscores: 10__10 (token '10__');
        - underscores adjacent to the period: 1010._1010 (token '1010._'), 1010_.1 (token '1010_.'), 1_.5 (token '1_.');
        - underscores adjacent to E / exponent sign / last exponent digit: 10.10E_-100_ (token '10.10E_'), 1.1E_5 (token
          '1.1E_'), 1.1E-_5 (token '1.1E-_'), 1.1E-5_ (token '1.1E-5_').
    NOTE: underscores do not affect data type and scale, e.g. isql output shows 10_10.10_10 as '1010.1010' with all four
    decimal digits, see also non_dec_int_resulting_types_test.py (C13 => INT64 with scale -4).
NOTES:
    [05.10.2026] pzotov
    Test was generated by zcode.ai.
    Commit: afba27964f368892b02f582b8ea68c512b7541ad.
    See also: doc/sql.extensions/README.decimal_and_non_decimal_literals.txt
    Checked on 6.0.0.2197-1e316df.
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    set bail off;
    select 10_10 v1, 1_234_567_890 v2, 1234567_890 v3 from rdb$database;
    select 10_10.10_10 v1, 1_000.5 v2, 1_23_45.6_78_09 v3 from rdb$database;
    select .5_5 v1, 0.5_5 v2 from rdb$database;
    select 10.10E-10_0 v1, -1_2_3_4_5.6E-1_0 v2 from rdb$database;
    select 12_345_678_901_234_567_890 v1 from rdb$database;
    -- forbidden: underscore before the first character...
    select _1010 err1 from rdb$database;
    select _1 err2 from rdb$database;
    -- ...and after the last character:
    select 100_ err3 from rdb$database;
    select 1__ err4 from rdb$database;
    -- two or more consecutive underscores:
    select 10__10 err5 from rdb$database;
    -- underscores before or after the period:
    select 1010._1010 err6 from rdb$database;
    select 1010_.1 err7 from rdb$database;
    select 1_.5 err8 from rdb$database;
    -- underscores before/after E and exponent sign, and after last exponent digit:
    select 10.10E_-100_ err9 from rdb$database;
    select 1.1E_5 err10 from rdb$database;
    select 1.1E-_5 err11 from rdb$database;
    select 1.1E-5_ err12 from rdb$database;
"""

substitutions = [('-Token unknown.*', '-Token unknown'),
                 ('At line.*', ''),
                 ('After line.*', ''),
                 ('[ \t]+', ' ')]

act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    V1 1010
    V2 1234567890
    V3 1234567890
    V1 1010.1010
    V2 1000.5
    V3 12345.67809
    V1 0.55
    V2 0.55
    V1 1.010000000000000e-99
    V2 -1.234560000000000e-06
    V1 12345678901234567890
"""

expected_stderr = """
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -_1
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -_1
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -100_
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1__
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -10__
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1010._
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1010_.
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1_.
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -10.10E_
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1.1E_
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1.1E-_
    Statement failed, SQLSTATE = 42000
    Dynamic SQL Error
    -SQL error code = -104
    -Token unknown
    -1.1E-5_
"""

@pytest.mark.version('>=6.0')
@pytest.mark.ai
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.expected_stderr = expected_stderr
    act.execute()
    assert (act.clean_stdout == act.clean_expected_stdout and
            act.clean_stderr == act.clean_expected_stderr)
