#coding:utf-8

"""
ID:          trigger.create-09
TITLE:       CREATE TRIGGER BEFORE INSERT DECLARE VARIABLE
DESCRIPTION:
FBTEST:      functional.trigger.create.09
"""

import pytest
from firebird.qa import *

init_script = """CREATE TABLE tb(id INT);
"""

db = db_factory(init=init_script)

test_script = """SET TERM ^;
CREATE TRIGGER test FOR tb BEFORE INSERT AS
DECLARE VARIABLE v1 SMALLINT;
DECLARE VARIABLE v2 INTEGER;
DECLARE VARIABLE v3 FLOAT;
DECLARE VARIABLE v4 DOUBLE PRECISION;
DECLARE VARIABLE v5 DECIMAL;
DECLARE VARIABLE v6 DECIMAL(4);
DECLARE VARIABLE v7 DECIMAL(4,2);
DECLARE VARIABLE v8 NUMERIC;
DECLARE VARIABLE v9 NUMERIC(5);
DECLARE VARIABLE v10 NUMERIC(5,3);
DECLARE VARIABLE v11 DATE;
DECLARE VARIABLE v12 TIME;
DECLARE VARIABLE v13 TIMESTAMP;
DECLARE VARIABLE v14 CHAR(1200);
DECLARE VARIABLE v15 CHAR(2000) CHARACTER SET WIN1250;
DECLARE VARIABLE v16 CHARACTER(3400);
DECLARE VARIABLE v17 CHARACTER VARYING(300);
DECLARE VARIABLE v18 NCHAR(1);
DECLARE VARIABLE v19 NATIONAL CHARACTER(30);
DECLARE VARIABLE v20 NATIONAL CHAR(130);
DECLARE VARIABLE v21 NATIONAL CHAR VARYING(30);
BEGIN
  new.id=1;
END^
SET TERM ;^
SHOW TRIGGER test;
"""

act = isql_act('db', test_script, substitutions=[('\\+.*', ''), ('\\=.*', ''), ('Trigger text.*', '')])

expected_stdout = """Triggers on Table TB:
TEST, Sequence: 0, Type: BEFORE INSERT, Active
AS
DECLARE VARIABLE v1 SMALLINT;
DECLARE VARIABLE v2 INTEGER;
DECLARE VARIABLE v3 FLOAT;
DECLARE VARIABLE v4 DOUBLE PRECISION;
DECLARE VARIABLE v5 DECIMAL;
DECLARE VARIABLE v6 DECIMAL(4);
DECLARE VARIABLE v7 DECIMAL(4,2);
DECLARE VARIABLE v8 NUMERIC;
DECLARE VARIABLE v9 NUMERIC(5);
DECLARE VARIABLE v10 NUMERIC(5,3);
DECLARE VARIABLE v11 DATE;
DECLARE VARIABLE v12 TIME;
DECLARE VARIABLE v13 TIMESTAMP;
DECLARE VARIABLE v14 CHAR(1200);
DECLARE VARIABLE v15 CHAR(2000) CHARACTER SET WIN1250;
DECLARE VARIABLE v16 CHARACTER(3400);
DECLARE VARIABLE v17 CHARACTER VARYING(300);
DECLARE VARIABLE v18 NCHAR(1);
DECLARE VARIABLE v19 NATIONAL CHARACTER(30);
DECLARE VARIABLE v20 NATIONAL CHAR(130);
DECLARE VARIABLE v21 NATIONAL CHAR VARYING(30);
BEGIN
  new.id=1;
END
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
"""

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.execute()
    assert act.clean_stdout == act.clean_expected_stdout
