#coding:utf-8

"""
ID:          n/a
TITLE:       Deleting record in master must cause deletions in appropriate detail if FK references to PK and 'ON DELETE CASCADE' option is used.
DESCRIPTION:
    Test verifies RI mechanism when ON DELETE CASCADE option is used.
    Parent table has PRIMARY KEY constraint.
    Child table has column(s) on which FK is declared, with option ON DELETE CASCADE.
    Single- and multi-segmented PK/FK are checked.
    Work within a single transaction.
NOTES:
    [21.06.2025] pzotov
    ::: NB :::
    SQL schema name (6.x+), single and double quotes are suppressed in the output.
    See $QA_HOME/README.substitutions.md or https://github.com/FirebirdSQL/firebird-qa/blob/master/README.substitutions.md

    Discussed with Vlad, letters 16.06.2025 13:54 (subj: "#8598: ...")
    Checked on 6.0.0.838; 3.0.13.33813.
"""

import pytest
from firebird.qa import *

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [('[ \t]+', ' ')]
for p in addi_subst_tokens.split():
    substitutions.append( (p, '') )

db = db_factory()
act = python_act('db', substitutions = substitutions)

expected_stdout = """
    REMAINED_IN_TDETL_CASE_1 0
    REMAINED_IN_TDETL_CASE_2 0
"""

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    
    test_sql = """
        set bail OFF;
        set list on;

        -- case-1: single segment PK:
        recreate table tmain(id int generated by default as identity primary key using index tmain_pk);
        recreate table tdetl(
            id int generated by default as identity primary key
            ,pid int
            ,constraint tdetl_fk foreign key(pid) references tmain
                ON DELETE CASCADE
        );
        insert into tmain(id) values(1);
        insert into tdetl(id, pid) values(100, 1);
        insert into tdetl(id, pid) values(101, 1);
        delete from tmain where id = 1; -- must PASS and cause deletion of all records in tdetl
        select count(*) as remained_in_tdetl_case_1 from tdetl;
        commit;
        drop table tdetl;
        drop table tmain;

        --------------------------------------------
        
        -- case-2: multi-segment PK:
        recreate table tmain(id1 int, id2 int, id3 int, primary key(id1, id2, id3) using index tmain_pk);
        recreate table tdetl(
            id int primary key
            ,pid1 int
            ,pid2 int
            ,pid3 int
            ,constraint tdetl_fk foreign key(pid1, pid2, pid3) references tmain
                ON DELETE CASCADE
        );
        insert into tmain(id1, id2, id3) values(1,1,1);
        insert into tdetl(id, pid1, pid2, pid3) values(200, 1, 1, 1);
        insert into tdetl(id, pid1, pid2, pid3) values(201, 1, 1, 1);
        delete from tmain where id1 = 1 and id2 = 1 and id3 = 1; -- must PASS and cause deletion of all records in tdetl
        select count(*) as remained_in_tdetl_case_2 from tdetl;
        commit;
        drop table tdetl;
        drop table tmain;
    """

    act.expected_stdout = expected_stdout
    act.isql(switches=['-q'], combine_output = True, input = test_sql)

    assert act.clean_stdout == act.clean_expected_stdout
