#coding:utf-8

"""
ID:          n/a
TITLE:       Attempt to update PK column(s) in master must fail if there is FK record in detail and FK was declared without CASCADE option
DESCRIPTION:
    Test verifies RI mechanism when CASCADE option missed: PK-column(s) in master may be updated
    only if there is no appropriate record in detail, i.e. with value in FK column(s) equal to PK value(s) from master.
    Single- and multi-segmented PK/FK are checked.
    Work within a single transaction.
NOTES:
    [17.06.2025] pzotov
    1. Extended 'subsitutions' list is used here to suppress "PUBLIC" schema prefix and remove single/double quotes from all object names. Need since 6.0.0.834.
       ::: NB :::
       File act.files_dir/'test_config.ini' must contain section:
           [schema_n_quotes_suppress]
           addi_subst="PUBLIC". " '
       (this file is used in qa/plugin.py, see QA_GLOBALS dictionary).

       Value of parameter 'addi_subst' is splitted on tokens using space character and we add every token to 'substitutions' list which
       eventually will be like this:
           substitutions = [ ( <optional: previous tuples>, ('"PUBLIC".', ''), ('"', ''), ("'", '') ]
    2. Adjusted expected output: removed single quotes from DB object name(s).

    Discussed with Vlad, letters 16.06.2025 13:54 (subj: "#8598: ...")
    Checked on 6.0.0.838; 3.0.13.33813.
"""

import pytest
from firebird.qa import *

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [('[ \t]+', ' ')]
for p in addi_subst_tokens.split():
    substitutions.append( (p, '') )

db = db_factory()
act = python_act('db', substitutions = substitutions)

expected_stdout = """
    Statement failed, SQLSTATE = 23000
    violation of FOREIGN KEY constraint TDETL_FK on table TDETL
    -Foreign key references are present for the record
    -Problematic key value is (ID = 1)
    REMAINED_MASTER_ID -2
    REMAINED_MASTER_ID 1
    REMAINED_DETAIL_ID 100
    REMAINED_DETAIL_ID 101

    Statement failed, SQLSTATE = 23000
    violation of FOREIGN KEY constraint TDETL_FK on table TDETL
    -Foreign key references are present for the record
    -Problematic key value is (ID1 = 1, ID2 = 1, ID3 = 1)
    REMAINED_MASTER_ID1 -2
    REMAINED_MASTER_ID2 -2
    REMAINED_MASTER_ID3 -2
    REMAINED_MASTER_ID1 1
    REMAINED_MASTER_ID2 1
    REMAINED_MASTER_ID3 1
    REMAINED_DETAIL_ID 100
    REMAINED_DETAIL_ID 101
"""

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    
    test_sql = """
        set bail OFF;
        set list on;

        -- case-1: single segment PK:
        recreate table tmain(id int generated by default as identity primary key using index tmain_pk);
        recreate table tdetl(id int generated by default as identity primary key, pid int, constraint tdetl_fk foreign key(pid) references tmain(id));
        insert into tmain(id) values(1);
        insert into tmain(id) values(2);
        insert into tdetl(id, pid) values(100, 1);
        insert into tdetl(id, pid) values(101, null);
        update tmain set id = -id where id = 1; -- must FAIL
        update tmain set id = -id where id = 2; -- must PASS
        select id as remained_master_id from tmain order by id;
        select id as remained_detail_id from tdetl order by id;
        commit;
        drop table tdetl;
        drop table tmain;
        --------------------------------------------


        -- case-2: multi-segment PK:
        recreate table tmain(id1 int, id2 int, id3 int, primary key(id1, id2, id3) using index tmain_pk);
        recreate table tdetl(id int primary key, pid1 int, pid2 int, pid3 int, constraint tdetl_fk foreign key(pid1, pid2, pid3) references tmain);
        insert into tmain(id1, id2, id3) values(1,1,1);
        insert into tmain(id1, id2, id3) values(1,1,2);
        insert into tdetl(id, pid1, pid2, pid3) values(100, 1, 1, 1);
        insert into tdetl(id, pid1, pid2, pid3) values(101, 1, 1, null);
        update tmain set id1 = -1, id2 = -1, id3 = -1 where id1 = 1 and id2 = 1 and id3 = 1; -- must FAIL
        update tmain set id1 = -2, id2 = -2, id3 = -2 where id1 = 1 and id2 = 1 and id3 = 2; -- must PASS
        select id1 as remained_master_id1, id2 as remained_master_id2, id3 as remained_master_id3 from tmain order by id1, id2, id3;
        select id as remained_detail_id from tdetl order by id;
        commit;
        drop table tdetl;
        drop table tmain;
    """

    act.expected_stdout = expected_stdout
    act.isql(switches=['-q'], combine_output = True, input = test_sql)

    assert act.clean_stdout == act.clean_expected_stdout
