#coding:utf-8

"""
ID:          n/a
TITLE:       Attempt to delete record in master must fail if there is FK record in detail and FK was declared without CASCADE option
DESCRIPTION:
    Test verifies RI mechanism when CASCADE option is used or missed: record in master may be deleted 
    only if there is no appropriate record in detail (with value in FK equal to PK value from master).
    Work within a single transaction
NOTES:
    [17.06.2025] pzotov
    1. Extended 'subsitutions' list is used here to suppress "PUBLIC" schema prefix and remove single/double quotes from all object names. Need since 6.0.0.834.
       ::: NB :::
       File act.files_dir/'test_config.ini' must contain section:
           [schema_n_quotes_suppress]
           addi_subst="PUBLIC". " '
       (this file is used in qa/plugin.py, see QA_GLOBALS dictionary).

       Value of parameter 'addi_subst' is splitted on tokens using space character and we add every token to 'substitutions' list which
       eventually will be like this:
           substitutions = [ ( <optional: previous tuples>, ('"PUBLIC".', ''), ('"', ''), ("'", '') ]
    2. Adjusted expected output: removed single quotes from DB object name(s).

    Discussed with Vlad, letters 16.06.2025 13:54 (subj: "#8598: ...")
    Checked on 6.0.0.838; 3.0.13.33813.
"""

import pytest
from firebird.qa import *

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [('[ \t]+', ' ')]
for p in addi_subst_tokens.split():
    substitutions.append( (p, '') )

db = db_factory()
act = python_act('db', substitutions = substitutions)

expected_stdout = """
    Statement failed, SQLSTATE = 23000
    violation of FOREIGN KEY constraint TDETL_FK on table TDETL
    -Foreign key references are present for the record
    -Problematic key value is (ID = 1)

    REMAINED_ID 1
"""

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    
    test_sql = """
        set bail OFF;
        set list on;
        recreate table tmain(id int generated by default as identity primary key using index tmain_pk);
        recreate table tdetl(id int generated by default as identity primary key, pid int, constraint tdetl_fk foreign key(pid) references tmain(id));
        insert into tmain(id) values(1);
        insert into tmain(id) values(2);
        insert into tdetl(id, pid) values(100, 1);
        insert into tdetl(id, pid) values(101, null);
        delete from tmain where id = 1; -- must FAIL
        delete from tmain where id = 2; -- must PASS
        select id as remained_id from tmain;
    """

    act.expected_stdout = expected_stdout
    act.isql(switches=['-q'], combine_output = True, input = test_sql)

    assert act.clean_stdout == act.clean_expected_stdout
