#coding:utf-8

"""
ID:          n/a
TITLE:       Child table must be updated even if current user has no privileges on it but 'SET NULL' present in FK declaration.
DESCRIPTION:
    Child table has column(s) on which FK is declared, with options: ON UPDATE SET NULL and ON DELETE SET NULL.
    Work within a single transaction.
NOTES:
    [21.06.2025] pzotov
    ::: NB :::
    SQL schema name (6.x+), single and double quotes are suppressed in the output.
    See $QA_HOME/README.substitutions.md or https://github.com/FirebirdSQL/firebird-qa/blob/master/README.substitutions.md

    Discussed with Vlad, letters 16.06.2025 13:54 (subj: "#8598: ...")
    Checked on 6.0.0.838; 3.0.13.33813.
"""

import pytest
from firebird.qa import *

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [('[ \t]+', ' '), ('(-)?At trigger\\s+\\S+', 'At trigger')]
for p in addi_subst_tokens.split():
    substitutions.append( (p, '') )

init_sql = """
    recreate table tmain(id int unique using index tmain_uk);
    recreate table tdetl(
        id int generated by default as identity
        ,pid int
        ,constraint tdetl_fk foreign key(pid) references tmain(id)
            ON DELETE SET NULL
            ON UPDATE SET NULL
    );
    commit;
    insert into tmain(id) values(1111);
    insert into tdetl(pid) values(1111);
    commit;
"""
db = db_factory(init = init_sql)
act = python_act('db', substitutions = substitutions)

tmp_user = user_factory('db', name='tmp_parent_only_accessor', password='123')

@pytest.mark.version('>=3.0')
def test_1(act: Action, tmp_user: User):
    
    test_sql = f"""
        set bail OFF;
        set wng off;
        set list on;
        -- set echo on;
        revoke all on all from {tmp_user.name};
        grant select, insert, update, delete on tmain to {tmp_user.name};
        commit;

        connect '{act.db.dsn}' user '{tmp_user.name}' password '{tmp_user.password}';
        select current_user as whoami from rdb$database;

        -- Update existsing record in parent which have references from detail.
        -- NB: detail table WILL BE CHANGED despite that current user has no any privilege on this table.
        -- New value in tdetl.pid will be NULL:
        update tmain set id = -9999;
        commit;

        connect '{act.db.dsn}' user '{act.db.user}' password '{act.db.password}';
        select 'point-1' as msg from rdb$database;
        set count on;
        select m.id as tmain_pk from tmain m;
        select d.id as tdetl_pk, d.pid as tdetl_pid from tdetl d;
        set count off;

        delete from tdetl;
        delete from tmain;
        insert into tmain(id) values(1111);
        insert into tdetl(pid) values(1111);
        commit;

        connect '{act.db.dsn}' user '{tmp_user.name}' password '{tmp_user.password}';

        -- NB: detail table WILL BE CHANGED despite that current user has no any privilege on this table.
        -- New value in tdetl.pid will be NULL:
        delete from tmain where id = 1111;
        commit;

        connect '{act.db.dsn}' user '{act.db.user}' password '{act.db.password}';
        select 'point-2' as msg from rdb$database;
        set count on;
        select m.id as tmain_pk from tmain m;
        select d.id as tdetl_pk, d.pid as tdetl_pid from tdetl d;
        set count off;
    """

    expected_stdout = f"""
        WHOAMI {tmp_user.name.upper()}
        MSG point-1
        
        TMAIN_PK -9999
        Records affected: 1

        TDETL_PK 1
        TDETL_PID <null>
        Records affected: 1

        MSG point-2
        
        Records affected: 0

        TDETL_PK 2
        TDETL_PID <null>
        Records affected: 1
    """

    act.expected_stdout = expected_stdout
    act.isql(switches=['-q'], combine_output = True, input = test_sql)

    assert act.clean_stdout == act.clean_expected_stdout
