#coding:utf-8

"""
ID:          n/a
TITLE:       FK definition: SET DEFAULT clause should not lead FK-columns to have their default values if parent record not exists or was removed
DESCRIPTION:
    Single- and multi-segmented PK/UK are checked.
    Work within a single transaction.
NOTES:
    [17.06.2025] pzotov
    1. Extended 'subsitutions' list is used here to suppress "PUBLIC" schema prefix and remove single/double quotes from all object names. Need since 6.0.0.834.
       ::: NB :::
       File act.files_dir/'test_config.ini' must contain section:
           [schema_n_quotes_suppress]
           addi_subst="PUBLIC". " '
       (this file is used in qa/plugin.py, see QA_GLOBALS dictionary).

       Value of parameter 'addi_subst' is splitted on tokens using space character and we add every token to 'substitutions' list which
       eventually will be like this:
           substitutions = [ ( <optional: previous tuples>, ('"PUBLIC".', ''), ('"', ''), ("'", '') ]
    2. Adjusted expected output: removed single quotes from DB object name(s).

    Discussed with Vlad, letters 16.06.2025 13:54 (subj: "#8598: ...")
    Checked on 6.0.0.838; 3.0.13.33813.
"""

import pytest
from firebird.qa import *

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [('[ \t]+', ' '), ('(-)?At trigger\\s+\\S+', 'At trigger')]
for p in addi_subst_tokens.split():
    substitutions.append( (p, '') )

db = db_factory()
act = python_act('db', substitutions = substitutions)

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    
    test_sql = """
        set bail OFF;
        set autoddl off;
        set list on;

        create domain dm_int_default int default -9999;

        -- case-1: single segment UK
        -- -------------------------
        recreate table tmain_single_uk(id int unique using index tmain_pk);
        recreate table tdetl_single_uk(
            id int generated by default as identity
            ,fk_id dm_int_default
            ,constraint tdetl_fk foreign key(fk_id) references tmain_single_uk(id)
                ON UPDATE SET DEFAULT
                ON DELETE SET DEFAULT
        );
        commit;
        insert into tmain_single_uk(id) values(1111);
        insert into tdetl_single_uk(fk_id) values(1111);
        commit;

        -- Update existsing record in parent which have references from detail.
        -- Must PASS because new value of ID equals to DEFAULT value for domain on which FK column is based:
        update tmain_single_uk set id = -9999;
        select * from tdetl_single_uk;
        rollback;

        -- Add record so that both 1111 and -9999 now exists in the parent table:
        insert into tmain_single_uk(id) values(-9999);
        -- must PASS because default value now exists in just inserted record.
        -- New value tdetl_single_uk.fk_id must become -9999:
        delete from tmain_single_uk where id = 1111;
        select * from tdetl_single_uk;
        rollback;

        -- Must fail because 'set default' cause FK column to have value = -9999 that not exists in the parent table:
        -- Statement failed, SQLSTATE = 23000
        -- violation of FOREIGN KEY constraint TDETL_FK on table TDETL_SINGLE_UK
        -- -Foreign key reference target does not exist
        -- -Problematic key value is (FK_ID = -9999)
        update tmain_single_uk set id = -8888;
        rollback;
        
        -- Must fail because 'set default' cause FK column to have value = -9999 that not exists in the parent table:
        -- Statement failed, SQLSTATE = 23000
        -- violation of FOREIGN KEY constraint TDETL_FK on table TDETL_SINGLE_UK
        -- -Foreign key reference target does not exist
        -- -Problematic key value is (FK_ID = -9999)
        delete from tmain_single_uk;
        commit;
        drop table tdetl_single_uk;
        drop table tmain_single_uk;

        --##############################


        -- case-2: multi segment UK
        -- -------------------------
        recreate table tmain_multi_uk(id1 int, id2 int, unique(id1, id2) using index tmain_uk);
        recreate table tdetl_multi_uk(
            id int generated by default as identity
            ,fk_id1 dm_int_default
            ,fk_id2 dm_int_default
            ,constraint tdetl_multi_fk foreign key(fk_id1, fk_id2) references tmain_multi_uk(id1, id2)
                ON UPDATE SET DEFAULT
                ON DELETE SET DEFAULT
        );
        commit;
        insert into tmain_multi_uk(id1, id2) values(1111, 2222);
        insert into tdetl_multi_uk(fk_id1, fk_id2) values(1111, 2222);
        commit;


        -- Update existsing record in parent which have references from detail.
        -- Must PASS because new value for ID1 and ID2 equals to DEFAULT value for domain on which FK columns are based:
        update tmain_multi_uk set id1 = -9999, id2 = -9999;
        select * from tdetl_multi_uk;
        rollback;


        insert into tmain_multi_uk(id1, id2) values(-9999, -9999);
        delete from tmain_multi_uk where id1 = 1111 and id2 = 2222;
        select * from tdetl_multi_uk;
        rollback;

        --+++++++++++++++++++++++++++++++++++++++++++++++++++
        -- Following three statements fail with same messages (all with SQLSTATE = 23000):
        -- violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -- -Foreign key references are >>> present <<< for the record
        -- -Problematic key value is (ID1 = 1111, ID2 = 2222)
        update tmain_multi_uk set id2 = null;
        update tmain_multi_uk set id1 = null;
        update tmain_multi_uk set id1 = null, id2 = null;


        -- Following three statements fail with same messages (all with SQLSTATE = 23000):
        -- violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -- -Foreign key reference >>> target <<< does not exist
        -- -Problematic key value is (FK_ID1 = -9999, FK_ID2 = -9999)
        -- -At trigger CHECK_*
        update tmain_multi_uk set id1 = 3333, id2 = null;
        update tmain_multi_uk set id1 = null, id2 = 4444;
        update tmain_multi_uk set id1 = 2222, id2 = 1111;
    """

    expected_stdout = """
        ID 1
        FK_ID -9999

        ID 1
        FK_ID -9999

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_FK on table TDETL_SINGLE_UK
        -Foreign key reference target does not exist
        -Problematic key value is (FK_ID = -9999)
        -At trigger CHECK_1

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_FK on table TDETL_SINGLE_UK
        -Foreign key reference target does not exist
        -Problematic key value is (FK_ID = -9999)
        -At trigger CHECK_2


        ID 1
        FK_ID1 -9999
        FK_ID2 -9999

        ID 1
        FK_ID1 -9999
        FK_ID2 -9999

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID1 = 1111, ID2 = 2222)

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID1 = 1111, ID2 = 2222)

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID1 = 1111, ID2 = 2222)

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key reference target does not exist
        -Problematic key value is (FK_ID1 = -9999, FK_ID2 = -9999)
        -At trigger CHECK_3

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key reference target does not exist
        -Problematic key value is (FK_ID1 = -9999, FK_ID2 = -9999)
        -At trigger CHECK_3

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key reference target does not exist
        -Problematic key value is (FK_ID1 = -9999, FK_ID2 = -9999)
        -At trigger CHECK_3
    """

    act.expected_stdout = expected_stdout
    act.isql(switches=['-q'], combine_output = True, input = test_sql)

    assert act.clean_stdout == act.clean_expected_stdout
