#coding:utf-8

"""
ID:          n/a
TITLE:       FK definition: SET NULL clause should not lead FK-columns to have NULLs.
DESCRIPTION:
    Parent table has UNIQUE constraint declared for NULLABLE column(s).
    Child table has column(s) on which FK is declared, with options: ON UPDATE SET NULL and ON DELETE SET NULL.
    Single- and multi-segmented PK/UK are checked.
    Work within a single transaction.
NOTES:
    [21.06.2025] pzotov
    ::: NB :::
    SQL schema name (6.x+), single and double quotes are suppressed in the output.
    See $QA_HOME/README.substitutions.md or https://github.com/FirebirdSQL/firebird-qa/blob/master/README.substitutions.md

    Discussed with Vlad, letters 16.06.2025 13:54 (subj: "#8598: ...")
    Checked on 6.0.0.838; 3.0.13.33813.
"""

import pytest
from firebird.qa import *

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [('[ \t]+', ' '), ('(-)?At trigger\\s+\\S+', 'At trigger')]
for p in addi_subst_tokens.split():
    substitutions.append( (p, '') )

db = db_factory()
act = python_act('db', substitutions = substitutions)

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    
    test_sql = """
        set bail OFF;
        set autoddl off;
        set list on;

        create domain dm_int_not_null int NOT NULL;

        -- case-1: single segment UK
        -- -------------------------
        recreate table tmain_single_uk(id int unique using index tmain_uk);
        recreate table tdetl_single_uk(
            id int generated by default as identity
            ,fk_id dm_int_not_null
            ,constraint tdetl_fk foreign key(fk_id) references tmain_single_uk(id)
                ON UPDATE SET NULL
                ON DELETE SET NULL
        );
        commit;
        insert into tmain_single_uk(id) values(1111);
        insert into tdetl_single_uk(fk_id) values(1111);
        commit;

        -- Fails with:
        -- SQLSTATE = 23000 / violation of FOREIGN KEY ... / Foreign key references are present / Problematic key value is (ID = 1111)
        -- ::: NB :::
        -- Behaviour here same as "ON UPDATE NO ACTION". Check for 'not null' (defined in domain) not occurs.
        update tmain_single_uk set id = null;
        rollback;

        insert into tmain_single_uk(id) values(null);
        -- Must fail with:
        -- Statement failed, SQLSTATE = 23000
        -- validation error for column TDETL_SINGLE_UK.FK_ID, value *** null ***
        -- At trigger CHECK_*
        delete from tmain_single_uk where id = 1111;
        rollback;
        
        -- Fails with:
        -- Statement failed, SQLSTATE = 23000
        -- validation error for column TDETL_SINGLE_UK.FK_ID, value *** null ***
        -- -At trigger CHECK_*
        delete from tmain_single_uk;
        commit;
        drop table tdetl_single_uk;
        drop table tmain_single_uk;

        --##############################

        -- case-2: multi segment UK
        -- -------------------------
        recreate table tmain_multi_uk(id1 int, id2 int, unique(id1, id2) using index tmain_uk);
        recreate table tdetl_multi_uk(
            id int generated by default as identity
            ,fk_id1 dm_int_not_null
            ,fk_id2 dm_int_not_null
            ,constraint tdetl_multi_fk foreign key(fk_id1, fk_id2) references tmain_multi_uk(id1, id2)
                ON UPDATE SET NULL
                ON DELETE SET NULL
        );
        commit;
        insert into tmain_multi_uk(id1, id2) values(1111, 2222);
        insert into tdetl_multi_uk(fk_id1, fk_id2) values(1111, 2222);
        commit;

        --+++++++++++++++++++++++++++++++++++++++++++++++++++
        -- Following three statements fail with same messages (all with SQLSTATE = 23000):
        -- violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -- -Foreign key references are present for the record
        -- -Problematic key value is (ID1 = 1111, ID2 = 2222)
        -- ::: NB :::
        -- Behaviour here same as "ON UPDATE NO ACTION". Check for 'not null' (defined in domain) not occurs.
        update tmain_multi_uk set id2 = null;
        update tmain_multi_uk set id1 = null;
        update tmain_multi_uk set id1 = null, id2 = null;
        --+++++++++++++++++++++++++++++++++++++++++++++++++++
        -- Following three statements fail with same messages (all with SQLSTATE = 23000):
        -- Statement failed, SQLSTATE = 23000
        -- validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -- -At trigger CHECK_*
        update tmain_multi_uk set id1 = 3333, id2 = null;
        update tmain_multi_uk set id1 = null, id2 = 4444;
        update tmain_multi_uk set id1 = 2222, id2 = 1111;

        rollback;

        -- Add record such that its columns not distinct from the pair of default values (defined for FK).
        insert into tmain_multi_uk(id1, id2) values(null, null);
        -- Now we try to remove record which currently is parent (id1 = 1111, id2 = 2222):
        -- Following statement must cause violation of domain check expression and fail with SQLSTATE = 23000:
        -- validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -- -At trigger CHECK_*
        delete from tmain_multi_uk where id1 = 1111 and id2 = 2222;
        rollback;

        -- Following statement must cause violation of domain check expression and fail with SQLSTATE = 23000:
        -- validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -- -At trigger CHECK_*
        delete from tmain_multi_uk;
        commit;
        drop table tdetl_multi_uk;
        drop table tmain_multi_uk;
    """

    expected_stdout = """
        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_FK on table TDETL_SINGLE_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID = 1111)

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_SINGLE_UK.FK_ID, value *** null ***
        -At trigger CHECK_2

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_SINGLE_UK.FK_ID, value *** null ***
        -At trigger CHECK_2


        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID1 = 1111, ID2 = 2222)

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID1 = 1111, ID2 = 2222)

        Statement failed, SQLSTATE = 23000
        violation of FOREIGN KEY constraint TDETL_MULTI_FK on table TDETL_MULTI_UK
        -Foreign key references are present for the record
        -Problematic key value is (ID1 = 1111, ID2 = 2222)

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -At trigger CHECK_3

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -At trigger CHECK_3

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -At trigger CHECK_3

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -At trigger CHECK_4

        Statement failed, SQLSTATE = 23000
        validation error for column TDETL_MULTI_UK.FK_ID1, value *** null ***
        -At trigger CHECK_4
    """

    act.expected_stdout = expected_stdout
    act.isql(switches=['-q'], combine_output = True, input = test_sql)

    assert act.clean_stdout == act.clean_expected_stdout
