#coding:utf-8

"""
ID:          n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/issues/438
TITLE:        BLOBs in external tables
DESCRIPTION:
    Attempt to create external table which has BLOB column must fail with
    'Data type BLOB is not supported for EXTERNAL TABLES' error, and this
    message has to contain name of the problem field.
JIRA:        CORE-116
FBTEST:      bugs.core_0116
NOTES:
    [10.09.2026] zcode.ai
    1. Re-implemented: avoid usage of $(DATABASE_LOCATION) macro (it is deprecated).
       Instead, test uses ConfigManager class from QA-plugin in order to preserve
       original content of databases.conf and restore it at the teardown stage
       (see sibling tests external_file_access_allowed_test.py, core_2796_test.py
       and core_2475_test.py which were re-implemented in the same way).
       Copy of $FB_HOME/databases.conf will be stored in the folder where test database lives.
       New content of this file will define alias that points to test DB file
       (see 'CONNECT_TO_ALIAS') and parameter for enabling creation of
       external table which storage is in the same folder as test DB uses:
           ExternalFileAccess = Restrict {test_db_path}
    2. One need to be sure that firebird.conf does NOT contain DatabaseAccess = None.
    3. The firebird.conf must contain 'ExternalFileAccess = None'.

    [11.09.2026] pzotov
    Reimplemented code, description and comments were generated by zcode.ai.
    Checked on 6.0.0.2176; 5.0.5.1862; 4.0.8.3314; 3.0.15.33884
"""

from pathlib import Path
import pytest
from firebird.qa import *

# Name of alias that will be written into temporary replacement of databases.conf:
CONNECT_TO_ALIAS = 'tmp_core_0116_alias'

# name of external table that will be used in SQL statements:
EXT_TABLE_NAME = 'ext_log'

db = db_factory()

# QA_GLOBALS -- dict, is defined in qa/plugin.py, obtain settings
# from act.files_dir/'test_config.ini':
#
addi_subst_settings = QA_GLOBALS['schema_n_quotes_suppress']
addi_subst_tokens = addi_subst_settings['addi_subst']

substitutions = [ ('line: \\d+, col: \\d+', '') ]
for p in addi_subst_tokens.split(' '):
    substitutions.append( (p, '') )

act = isql_act('db', substitutions = substitutions)

@pytest.mark.ai
@pytest.mark.version('>=3.0')
def test_1(act: Action, store_config: ConfigManager):

    # Obtain the physical database location.
    # NOTE: we must NOT use 'act.db.db_path' for ALIASED databases! It will return '.' rather than full path+filename.
    # Use only con.info.name for that:
    TEMP_DB_CONF_CONTENT = ''

    with act.db.connect() as con:
        test_db_file = con.info.name
        test_db_path = Path(test_db_file).parent
        TEMP_DB_CONF_CONTENT = f"""
            {CONNECT_TO_ALIAS} = {test_db_file}
            {{
                ExternalFileAccess = Restrict {test_db_path}
            }}
        """
    assert CONNECT_TO_ALIAS in TEMP_DB_CONF_CONTENT and 'ExternalFileAccess' in TEMP_DB_CONF_CONTENT

    # REPLACE databases.conf:
    store_config.replace('databases.conf', TEMP_DB_CONF_CONTENT)

    # Storage of external table would be in the SAME directory as test DB uses
    # (though its creation must FAIL, see expected_stderr):
    ext_file = test_db_path / 'z.dat'

    # Remove leftovers from an interrupted/failed previous test run.
    ext_file.unlink(missing_ok=True)

    external_file = str(ext_file).replace("'", "''")

    test_sql = f"""
        set bail on;
        connect 'localhost:{CONNECT_TO_ALIAS}' user {act.db.user} password '{act.db.password}';
        create table {EXT_TABLE_NAME} external file '{external_file}'(f1 int, f2 blob sub_type text);
    """

    act.expected_stderr = f"""
        Statement failed, SQLSTATE = HY004
        unsuccessful metadata update
        -CREATE TABLE {EXT_TABLE_NAME.upper()} failed
        -SQL error code = -607
        -Invalid command
        -Data type BLOB is not supported for EXTERNAL TABLES. Relation '{EXT_TABLE_NAME.upper()}', field 'F2'
    """

    act.isql(switches=['-q'], connect_db = False, credentials = False, input = test_sql)
    ext_file.unlink(missing_ok = True)

    assert act.clean_stderr == act.clean_expected_stderr
