#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/3186
TITLE:       DB_KEY is always zero for external tables
DESCRIPTION:
    [text generated by zcode.ai]
    DB_KEY of external table rows must be usable in queries: we select
    rdb$db_key of the last inserted row ('col' ordered descending) and
    use it in WHERE clause to check value of 'col' for that row.
    Difference between stored timestamp and timestamp that was used
    during INSERT must be exactly zero milliseconds.
JIRA:         CORE-2796
FBTEST:       bugs.core_2796
NOTES:
    [10.09.2026] zcode.ai
    1. Re-implemented: avoid usage of $(DATABASE_LOCATION) macro (it is deprecated)
       and avoid requirement 'ExternalFileAccess = Full' in firebird.conf.
       Instead, test uses ConfigManager class from QA-plugin in order to preserve
       original content of databases.conf and restore it at the teardown stage
       (see sibling test functional/table/external/external_file_access_allowed_test.py
       which was re-implemented in the same way).
       Copy of $FB_HOME/databases.conf will be stored in the folder where test database lives.
       New content of this file will define alias that points to test DB file
       (see 'CONNECT_TO_ALIAS') and parameter for enabling creation of
       external table which storage is in the same folder as test DB uses:
           ExternalFileAccess = Restrict {test_db_path}
    2. One need to be sure that firebird.conf does NOT contain DatabaseAccess = None.
    3. The firebird.conf must contain 'ExternalFileAccess = None'.

    [11.09.2026] pzotov
    Reimplemented code, description and comments were generated by zcode.ai.
    Checked on 6.0.0.2176; 5.0.5.1862; 4.0.8.3314; 3.0.15.33884
"""

from pathlib import Path
import pytest
from firebird.qa import *

# Name of alias that will be written into temporary replacement of databases.conf:
CONNECT_TO_ALIAS = 'tmp_core_2796_alias'

# name of external table that will be used in SQL statements:
EXT_TABLE_NAME = 'ext_test'

db = db_factory()
substitutions = [('[ \t]+', ' ')]
act = isql_act('db', substitutions = substitutions)

@pytest.mark.ai
@pytest.mark.version('>=3.0')
def test_1(act: Action, store_config: ConfigManager, capsys):

    # Obtain the physical database location.
    # NOTE: we must NOT use 'act.db.db_path' for ALIASED databases! It will return '.' rather than full path+filename.
    # Use only con.info.name for that:
    TEMP_DB_CONF_CONTENT = ''
    with act.db.connect() as con:
        test_db_file = con.info.name
        test_db_path = Path(test_db_file).parent
        TEMP_DB_CONF_CONTENT = f"""
            {CONNECT_TO_ALIAS} = {test_db_file}
            {{
                ExternalFileAccess = Restrict {test_db_path}
            }}
        """
    assert CONNECT_TO_ALIAS in TEMP_DB_CONF_CONTENT and 'ExternalFileAccess' in TEMP_DB_CONF_CONTENT

    # REPLACE databases.conf:
    store_config.replace('databases.conf', TEMP_DB_CONF_CONTENT)

    # Storage of external table will be in the SAME directory as test DB uses:
    ext_file = test_db_path / 'c2796.dat'

    # Remove leftovers from an interrupted/failed previous test run.
    ext_file.unlink(missing_ok=True)

    external_file = str(ext_file).replace("'", "''")

    test_sql = f"""
        set bail on;
        set list on;
        connect 'localhost:{CONNECT_TO_ALIAS}' user {act.db.user} password '{act.db.password}';
        recreate table {EXT_TABLE_NAME} external file '{external_file}'(col char(24), lf char(1));
        commit;
        set term ^;
        execute block returns (ms_diff bigint)
        as
            declare dbkey char(8) character set octets;
            declare v_dts1 timestamp;
        begin
            v_dts1=cast('now' as timestamp);
            insert into {EXT_TABLE_NAME} values( :v_dts1-rand()*100, ascii_char(10));
            insert into {EXT_TABLE_NAME} values( :v_dts1-rand()*100, ascii_char(10));
            insert into {EXT_TABLE_NAME} values( :v_dts1-rand()*100, ascii_char(10));
            insert into {EXT_TABLE_NAME} values( :v_dts1,            ascii_char(10));
            insert into {EXT_TABLE_NAME} values( :v_dts1-rand()*100, ascii_char(10));

            select rdb$db_key from {EXT_TABLE_NAME} order by col desc rows 1 into :dbkey;

            for
                select datediff(millisecond from cast(col as timestamp) to :v_dts1)
                from {EXT_TABLE_NAME}
                where rdb$db_key = :dbkey
                into ms_diff
            do
                suspend;
        end
        ^
        set term ;^
    """

    act.expected_stdout = f"""
        MS_DIFF 0
    """

    act.isql(switches=['-q'], connect_db = False, credentials = False, input = test_sql, combine_output = True)
    ext_file.unlink(missing_ok = True)

    assert act.clean_stdout == act.clean_expected_stdout
