#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/6413
TITLE:       Data pages of newly gbak restored databases should be marked as "swept"
DESCRIPTION:
    Test adds a table and fill it with some data.
    Then we make b/r and obtain statistics using 'gstat -d ...'
    Output will contain lines like: "Primary pages: 1, secondary pages: 1, swept pages: 1"
    We have to check that in every such line value of primary pages is equal to swept pages
    or it can be greater but NO MORE than for <MAX_NUM_OF_EMPTY_PAGES> because of pages
    allocation algorithm.
    Explained by Vlad, 17.07.2025 16:34.
NOTES:
    [17.07.2025] pzotov
        Commits:
        5.x (25.06.2025 2054): a0e23c32251c2257c4e3b13d0a9fd98a29a16dec // Back-ported pull request #8549
        6.x (25.06.2025 1905): 564c98b2e0854be949166ee369128208af32eec5
    [17.01.2026] pzotov
        One need to explicitly DISABLE parallel workers during restore because otherwise test can fail
        in approx 3-4% of runs on Classic: difference between primary and swept pages GREATER than
        <MAX_NUM_OF_EMPTY_PAGES> can appear.
        Default value of parallel workers (in firebird.conf) may be greater than 1, so we have to run
        srv.database.restore() with explicitly specified 'parallel_workers=1'.
        This ability absent in local_restore() method thus it was decided to run restore using common way.
        Big thanks Vlad for suggestion.

        Confirmed on 6.0.0.858 ; 5.0.3.1668
        Checked on 6.0.0.876; 6.0.0.1394 ; 5.0.3.1673; 5.0.4.1746
"""
import string
import locale
import re
from pathlib import Path
from firebird.driver import SrvRestoreFlag

import pytest
from firebird.qa import *

init_sql = """
    set bail on;
    recreate table test(id int generated by default as identity, s varchar(32760));
    set term ^;
    execute block as
        declare n int = 1000;
        declare i int = 0;
    begin
        while (i < n) do
        begin
            insert into test(s) values(lpad('', rand()*32760, uuid_to_char(gen_uuid())));
            i = i + 1;
        end
    end^
    set term ;^
    commit;
"""
db = db_factory(init = init_sql, charset = 'win1251', page_size = 8192)

act = python_act('db')

fbk_file = temp_file('gh_6413.fbk')

#-----------------------------------------------------------

REMOVE_PUNCT = str.maketrans('', '', string.punctuation)
MAX_NUM_OF_EMPTY_PAGES = 7
EXPECTED_MSG = f'Expected: no lines with difference between primary and swept pages GREATER than {MAX_NUM_OF_EMPTY_PAGES}'

@pytest.mark.version('>=5.0.3')
def test_1(act: Action, fbk_file: Path, capsys):

    with act.connect_server(encoding=locale.getpreferredencoding()) as srv:
        srv.database.backup(database=act.db.db_path, backup=fbk_file)
        # NOTE: backup method is **(ASYNC service)** (see firebird driver source).
        # We have to call wait() here otherwise exception raises:
        # self._srv()._svc.start(spb.get_buffer()) --> firebird.driver.types.DatabaseError: Service is currently busy: Restore Database
        srv.wait()

        srv.database.restore(backup=fbk_file, database=act.db.db_path, flags=SrvRestoreFlag.REPLACE, parallel_workers=1)
        srv.wait()

    act.gstat(switches=['-d' ], io_enc = locale.getpreferredencoding())
    # Primary pages: 1, secondary pages: 1, swept pages: 1
    #   0       1    2      3       4    5    6      7   8
    p_swept_pages = re.compile(r'Primary pages(:)?\s+\d+.*swept pages(:)?\s+\d+', re.IGNORECASE)
    non_swept_line_indices = []
    for idx, line in enumerate(act.stdout.splitlines()):
        if p_swept_pages.search(line):
            tokens = line.split()
            if len(tokens) >= 9:
                try:
                    primary_pages_count = int(tokens[2].translate(REMOVE_PUNCT))
                    swept_pages_count = int(tokens[8].translate(REMOVE_PUNCT))
                    if primary_pages_count - swept_pages_count > MAX_NUM_OF_EMPTY_PAGES:
                        non_swept_line_indices.append( (idx, line) )
                except ValueError as e:
                    print(e.__str__())
            else:
                print('Line does not contain all expected tokens: "{line=}"')

    if non_swept_line_indices:
        print(f'At least one line contains difference between primary and swept pages GREATER than {MAX_NUM_OF_EMPTY_PAGES}:')
        for p in non_swept_line_indices:
            print(f'Line #{p[0]}, text: {p[1].strip()}')
    else:
        print(EXPECTED_MSG)

    act.expected_stdout = EXPECTED_MSG
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
