#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/8965
TITLE:       Wrong PERCENT_RANK computation
DESCRIPTION:
    Test creates GTT for <N_CHECKS> generatings of random data.
    On each check we add <N_ROWS> into this table and evaluate PERCENT RANK
    for each value using two ways: 
        * by applying percent_rank()over(order by val);
        * by evaluating result using formula (RANK-1) / (TOTAL_ROWS - 1).
    Resulting values of percent rank have type DOUBLE PRECISION thus we have
    to compare them with allowing some small mismatch.
    No mismatches with absolute value greater than {MAX_DIFF_ABS} must occur.
    Otherwise test prints data from test table and result of comparison.
NOTES:
    [01.04.2026] pzotov
    Confirmed bug on 6.0.0.1867; 5.0.4.1793; 4.0.7.3263.
    Checked on 6.0.0.1870; 5.0.4.1796; 4.0.7.3264.
"""
import pytest
from firebird.qa import *

db = db_factory()

###############
N_CHECKS = 100
N_ROWS = 30
MAX_DIFF_ABS = 0.0000000000001
###############

test_script = f"""
    set bail on;
    recreate global temporary table data(
        id int generated by default as identity constraint pk_data primary key,
        val int128
    ) on commit delete rows;

    set term ^;
    create procedure sp_check returns(
        id type of column data.id
       ,val type of column data.val
       ,percent_rank_calc double precision
       ,percent_rank_func double precision
    ) as
    begin
        for
            with
            one as (
                select
                     id
                    ,val
                    ,rank()over(order by val) as rnk
                    ,count(*)over()-1 as cnt
                from data 
            )
            ,two as (
                select
                    one.*
                    ,iif(rnk = 1, 0, cast(1.0 as double precision) * (rnk-1)/cnt) as percent_rank_calc
                from one 
            )
            ,chk as (
                select id, val, percent_rank()over(order by val) as percent_rank_func
                from data
            )
            select
                a.id
               ,a.val
               ,a.percent_rank_calc
               ,b.percent_rank_func
            from two a
            join chk b using(id)
            where abs(a.percent_rank_calc - b.percent_rank_func) > {MAX_DIFF_ABS}
        into
            id, val, percent_rank_calc, percent_rank_func
        do
            suspend;
    end
    ^

    execute block as
        declare n_chk int = {N_CHECKS};
        declare n_rows int = {N_ROWS};
        declare i int = 0;
        declare r double precision;
        declare v int128;
        declare v128min int128 = -170141183460469231731687303715884105728;
        declare v128max int128 = 170141183460469231731687303715884105727;
    begin
        while (n_chk > 0) do
        begin
            delete from data;
            i = 0;
            while (i < n_rows) do
            begin
                r = rand();
                if (r < 0.1) then
                    v = 0;
                else if (r < 0.2) then
                    v = null;
                else if (r < 0.3) then
                    v = v128min;
                else if (r < 0.4) then
                    v = v128max;
                else if (r < 0.5) then
                    v = -9223372036854775808;
                else if (r < 0.6) then
                    v = 9223372036854775807;
                else if (r < 0.7) then
                    v = -rand() * v128max;
                else 
                    v = rand() * v128max;

                insert into data(val) values(:v);
                i = i + 1;
            end

            if ( exists(select 1 from sp_check) ) then
                leave;
            else
                delete from data;

            n_chk = n_chk - 1;
        end

    end ^
    set term ;^

    set count on;
    -- These both must NOT show rows:
    select * from data;
    select * from sp_check;
"""

act = python_act('db')

@pytest.mark.version('>=4.0.7')
def test_1(act: Action, capsys):
    act.expected_stdout = """
        Records affected: 0
        Records affected: 0
    """
    act.isql(switches=['-q', '-pag', '0'], input = test_script, combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
