#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/8890
TITLE:       WITH TIME ZONE types store non-zero garbage for padding instead of 0x00.
DESCRIPTION:
    Test creates external table to store there data of types: 'timestamp with time zone', 'time with time zone'.
    Then we open appropriate file as binary, parse its content and check that final two bytes of record that
    stores 'time[stamp] with time zone' value are 0x0 (see 'pad_bytes').
NOTES:
    [12.09.2026] zcode.ai
    Re-implemented: avoid usage of temp_file() as storage for external tables.
    Test uses ConfigManager class from QA-plugin in order to preserve original
    content of databases.conf and restore it at the teardown stage
    (see sibling tests external_file_access_allowed_test.py, core_2796_test.py etc).
    Copy of $FB_HOME/databases.conf will be stored in the folder where test database lives.
    New content of this file will define alias that points to test DB file
    (see 'CONNECT_TO_ALIAS') and parameter for enabling creation of
    external tables which storage is in the same folder as test DB uses:
        ExternalFileAccess = Restrict {test_db_path}
    isql connects to this ALIAS with 'localhost:' prefix.
    Both external files ('gh_8890_ts_tz.dat' and 'gh_8890_tm_tz.dat') now are
    created in the SAME directory as test DB uses.

    [12.09.2026] pzotov
    Reimplemented code, description and comments were generated by zcode.ai.
    Checked on 6.0.0.2176.
"""
import time
import struct

import pytest
from pathlib import Path
from firebird.qa import *

db = db_factory()

act = python_act('db')

DATE_BIN_LEN = 4

# Name of alias that will be written into temporary replacement of databases.conf:
CONNECT_TO_ALIAS = 'tmp_gh_8890_alias'

@pytest.mark.ai
@pytest.mark.version('>=6.0')
def test_1(act: Action, store_config: ConfigManager, capsys):

    # Obtain the physical database location.
    # NOTE: we must NOT use 'act.db.db_path' for ALIASED databases! It will return '.' rather than full path+filename.
    # Use only con.info.name for that:
    TEMP_DB_CONF_CONTENT = ''
    with act.db.connect() as con:
        test_db_file = con.info.name
        test_db_path = Path(test_db_file).parent
        TEMP_DB_CONF_CONTENT = f"""
            {CONNECT_TO_ALIAS} = {test_db_file}
            {{
                ExternalFileAccess = Restrict {test_db_path}
            }}
        """
    assert CONNECT_TO_ALIAS in TEMP_DB_CONF_CONTENT and 'ExternalFileAccess' in TEMP_DB_CONF_CONTENT

    # REPLACE databases.conf:
    store_config.replace('databases.conf', TEMP_DB_CONF_CONTENT)

    # Item with index=0 of every tuple now points to file which is located in the
    # SAME directory as test DB uses (instead of temp_file() that was used before),
    # i.e. inside the directory that is allowed by per-alias
    # ExternalFileAccess = Restrict (see TEMP_DB_CONF_CONTENT above):
    x_types_map = {
        'timestamp' : (Path(f'{test_db_path}') / 'gh_8890_ts_tz.dat', '2026-02-08 14:32:13.4567 Pacific/Samoa', DATE_BIN_LEN)
       ,'time'      : (Path(f'{test_db_path}') / 'gh_8890_tm_tz.dat', '14:32:13.4567 Pacific/Fiji'            ,      0      )
    }
    fails_cnt = 0

    for xtype_name, v in x_types_map.items():

        x_ext_file, xdts, xtime_offset = v[:3]
        x_fld_type = xtype_name + ' with time zone'

        # ----------------------------------
        x_ext_file.unlink(missing_ok = True)
        # ----------------------------------
        test_dml = f"""
            set bail on;
            connect 'localhost:{CONNECT_TO_ALIAS}' user {act.db.user} password '{act.db.password}';
            recreate table tsz_ext external '{x_ext_file}' (
               tmz {x_fld_type}
              ,eol char(2) character set ascii default '--'
            );
            commit;
            insert into tsz_ext(tmz) values ('{xdts}');
            commit;
        """
        act.isql(switches=['-q'], connect_db = False, credentials = False, input = test_dml, charset='utf8', io_enc = 'utf-8', combine_output = True)
        assert act.clean_stdout == ''
        act.reset()

        #---+++***---+++***---+++***---+++***---+++***---+++***---+++***---+++***---+++***---+++***---+++***

        with open(x_ext_file, 'rb') as f:
            ext_raw_data = f.read()

        rec_bytes = xtime_offset + 8 + 2
        for row_idx in range(len(ext_raw_data)//rec_bytes):

            # https://github.com/FirebirdSQL/firebird/issues/8890
            # "WITH TIME ZONE types store non-zero garbage for padding instead of 0x00"
            #
            pad_bytes = struct.unpack_from('@H', ext_raw_data[row_idx * rec_bytes + xtime_offset + 6 : row_idx * rec_bytes + xtime_offset + 8])[0]
            if pad_bytes != 0:
                print(f"Garbage found for {xtype_name=}, actual padding bytes: {hex(pad_bytes)}")
                fails_cnt = fails_cnt + 1

    # Remove storages of external tables (they exist because INSERT was committed):
    for v in x_types_map.values():
        v[0].unlink(missing_ok = True)

    expected_msg = f'ALL FINE for {row_idx+1} rows'
    if fails_cnt == 0:
        print(expected_msg)

    act.expected_stdout = f"""
        {expected_msg}
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
    act.reset()
