#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/pull/8940
TITLE:       Better cardinality estimation for queries with many predicates (especially those not matched to any indices)
DESCRIPTION:
    Test creates a table with 4 integer columns (F01 ... F04) and adds there <TOTAL_ROWS_COUNT> rows.
    Generated numbers are random but resulting selectivity NOT LESS than 1/50 and NOT GREATER than 1/N where <N> differs
    for each of these columns. The name of column with worst/best selectivity can *not* be predicted: for one run such
    column can be 'F04' while at second run it can be 'F02' etc.
    After table is filled, we invoke RDB$SQL.EXPLAIN() with requirement cardinality (for each node of explained plan) of
    following query: 'SELECT COUNT(*) FROM TEST WHERE F03=? AND F04=? AND F01=? AND F02=?'.
    
    Explained plan of this query will always contain lines with 'Bitmap And' and (after each of such line) names of indices
    that have been involved in such action.
    Also, output of RDB$SQL.EXPLAIN() contains 'CARDINALITY' column for each node of plan. We are interesting only for LAST
    occurrence of not-null value in this column because it shows ESTIMATION of cardinality for overall result of 
    'Bitmap And' actions (against all involve indices), see 'cardinality_evaluated'.

    We parse such lines and collect *each* name of index that participates in 'bitmap and' operation (see 'idx_scan_ptn').
    Name of schema ("PUBLIC") is cutted-off from each index name. List of these indices has name 'idx_scan_lst'.

    Then we obtain selectivity for each index from 'idx_scan_lst' and fill 'selectivity_map' dict, with further sorting this
    dict for values (i.e. selectivity) in ascending order.

    We calculate overall selectivity of all "Bitmaps And" actions using formula from ticket, see 'exponent_selectivity'.
    This value has name 'cardinality_via_exp'. It is compared with previously obtained 'cardinality_evaluated'.
    Test may be considered as PASSED if ABS() of difference between these values not greater than <MAX_CARD_DIFF_PRC> percent.

    Otherwise we show all data that may be interested. Content of the 'TEST' table is shown in form of INSERT statements, i.e.
    'INSERT INTO TEST(...) VALUES(...)' - to make investigation easy.
NOTES:
    [31.03.2026] pzotov
    Thanks to dimitr for suggestions and explanations related to this test.
    Confirmed problem (poor cardinality estimation) on 6.0.0.1816.
    Checked on 6.0.0.1858.
"""

import re
from math import *
import random
from pathlib import Path
from firebird.driver import DatabaseError

import pytest
from firebird.qa import *

######################
TOTAL_ROWS_COUNT = 10000
MAX_CARD_DIFF_PRC = 15
######################

init_sql = f"""
    set bail on;
    set autoterm on;
    create table test(
        id int128 generated by default as identity
       ,f01 int128
       ,f02 int128
       ,f03 int128
       ,f04 int128
    );
    execute block as
        declare n int = {TOTAL_ROWS_COUNT};
        declare v_max_01 int;
        declare v_max_02 int;
        declare v_max_03 int;
        declare v_max_04 int;
    begin
        v_max_01 = maxvalue(50, cast(rand() * 1000 as int));
        v_max_02 = maxvalue(50, cast(rand() * 500 as int));
        v_max_03 = maxvalue(50, cast(rand() * 250 as int));
        v_max_04 = maxvalue(50, cast(rand() * 125 as int));

        for 
            -- query to use `v_max_nn` values in mod() expressions in RANDOM ORDER
            -- (otherwise `f01` will have better selectivity much often then `f02` etc):
            select
                 max(iif(i=1,r,null)) as v_max_01
                ,max(iif(i=2,r,null)) as v_max_02
                ,max(iif(i=3,r,null)) as v_max_03
                ,max(iif(i=4,r,null)) as v_max_04
            from (
                select row_number()over(order by rand()) i, r
                from
                (
                    select :v_max_01 as r from rdb$database union all
                    select :v_max_02 as r from rdb$database union all
                    select :v_max_03 as r from rdb$database union all
                    select :v_max_04 as r from rdb$database
                )
            )
        as cursor c
        do begin
            while (n > 0) do
            begin
                insert into test(f01, f02, f03, f04)
                values(
                     mod( cast(rand() * {TOTAL_ROWS_COUNT} as int), iif(rand() < 0.1, null, c.v_max_01) )
                    ,mod( cast(rand() * {TOTAL_ROWS_COUNT} as int), iif(rand() < 0.1, null, c.v_max_02) )
                    ,mod( cast(rand() * {TOTAL_ROWS_COUNT} as int), iif(rand() < 0.1, null, c.v_max_03) )
                    ,mod( cast(rand() * {TOTAL_ROWS_COUNT} as int), iif(rand() < 0.1, null, c.v_max_04) )
                );
                n = n - 1;
            end
        end
    end
    ;
    commit;

    -- ::: ACHTUNG ::: DO NOT CHANGE INDICES NAMES: TEST_F01 ... TEST_F04
    -- They are used in the pattern 'idx_scan_ptn':
    create index test_f01 on test(f01);
    create index test_f02 on test(f02);
    create index test_f03 on test(f03);
    create index test_f04 on test(f04);
    commit;
"""

db = db_factory(init = init_sql)
act = python_act('db', substitutions=[('[ \t]+', ' ')])

#-----------------------------------------------------------

def replace_leading(source, char="."):
    stripped = source.lstrip()
    return char * (len(source) - len(stripped)) + stripped

#-----------------------------------------------------------

@pytest.mark.version('>=6.0')
def test_1(act: Action, capsys):

    selectivity_map = {}
    sql_explain_lines = []
    with act.db.connect() as con:
        cur = con.cursor()
        chk_sql = """
            select
                 plan_line as rn
                ,cardinality
                ,cast(access_path as varchar(32760)) as access_txt
            from rdb$sql.explain(q'#select count(*) from test where f03=? and f04=? and f01=? and f02=?#')
        """

        # Examples of output:
        # -------------------
        # RN                              1
        # CARDINALITY                     <null>
        # ACCESS_TXT                      Select Expression
        #  
        # RN                              2
        # CARDINALITY                     1.000000000000000
        # ACCESS_TXT                      -> Aggregate
        #  
        # RN                              3
        # CARDINALITY                     0.01570275331132235
        # ACCESS_TXT                      -> Filter
        # 
        # RN                              4
        # CARDINALITY                     1.570275331132235 <<<  WE HAVE TO OBTAIN THIS VALUE (LAST OCCURRENCE OF 'CARDINALITY')
        # ACCESS_TXT                      -> Table "PUBLIC"."TEST" Access By ID
        #     -> Bitmap And
        #         -> Bitmap
        #             -> Index "PUBLIC"."TEST_F01" Range Scan (full match) <<< WE HAVE TO COLLECT NAMES OF USED INDICES, HERE: 'TEST_F01' 
        #         -> Bitmap
        #             -> Index "PUBLIC"."TEST_F02" Range Scan (full match) <<< WE HAVE TO COLLECT NAMES OF USED INDICES, HERE: 'TEST_F02' 
        # -------------------

        # Indices with names that occur in thsi output will be stored in the list 'idx_scan_lst'
        # We use pattern to parse output related to index handling (here it is "Index <name> Range Scan"), e.g.:
        # '-> Index "PUBLIC"."TEST_F01" Range Scan (full match)'
        #
        idx_scan_ptn = re.compile( 'Index (("PUBLIC"|("SYSTEM")).)?(")?TEST_F\\d+(")?\\s+Range\\s+Scan')
        idx_scan_lst = []
        cardinality_evaluated = 0
        try:
            cur.execute(chk_sql)
            cur_cols = cur.description
            for r in cur:
                for i in range(0,len(cur_cols)):
                    sql_explain_line_i = ''
                    if cur_cols[i][0] == 'CARDINALITY':
                        cardinality_for_this_node = r[i]
                    if cur_cols[i][0] == 'ACCESS_TXT':
                        sql_explain_line_i = cur_cols[i][0] + ' : ' + '\n'.join([replace_leading(s) for s in r[i].split('\n')])
                        for line in r[i].splitlines():
                            if idx_scan_ptn.search(line):
                                # Index "PUBLIC"."TEST_F01" Range Scan (full match) --> Index "PUBLIC"."TEST_F01"
                                idx_prefix = idx_scan_ptn.search(line).group()
                                idx_prefix = idx_prefix.replace('"PUBLIC".', '').replace('"SYSTEM".', '')
                                idx_scan_lst.append( idx_prefix.replace('"', '').split()[1] ) # add name of index
                                cardinality_evaluated = cardinality_for_this_node
                    else:
                        sql_explain_line_i = cur_cols[i][0] + ' : ' + str(r[i])

                    sql_explain_lines.append(sql_explain_line_i)
        except DatabaseError as e:
            print(e.__str__())
            print(e.gds_codes)

        assert idx_scan_lst, "Could not properly parse output of rdb$sql.explain(): no lines matching 'Index Range Scan' pattern."
        assert cardinality_evaluated, "Could not find CARDINALITY value in the output of RDB$SQL.EXPLAIN()."

        cur.execute(
            """
                select
                    trim(ri.rdb$index_name)
                   ,ri.rdb$statistics
                from rdb$indices ri
                where
                    ri.rdb$relation_name = upper('test')
            """
        )

        for r in cur:
            if r[0].strip() in idx_scan_lst:
                selectivity_map[ r[0] ] = r[1]

        assert selectivity_map, 'No records found in rdb$indices, map is empty. Check query.'

    # < with ... con

    exponent_selectivity = 1
    for i,v in enumerate(sorted(selectivity_map.values())):
        exponent_selectivity *= v ** (1/(2**i))

    cardinality_via_exp = exponent_selectivity * TOTAL_ROWS_COUNT

    EXPECTED_MSG = 'Expected.'
    if abs(100 * cardinality_evaluated / cardinality_via_exp - 100) < MAX_CARD_DIFF_PRC:
        print(EXPECTED_MSG)
    else:
        print(f'Cardinality value in the RDB$SQL.EXPLAIN() vs calculated one differs for more than {MAX_CARD_DIFF_PRC}%:')
        print(f"CARDINALITY specified for indices involved in 'Bitmap And':  {cardinality_evaluated}")
        print(f'CARDINALITY calculated via selectivity on exponential basis: {cardinality_via_exp}')
        print(f'Used indices (in ascending order of their selectivity):')
        for k,v in sorted(selectivity_map.items(), key=lambda item: item[1]):
            print(k, ':::', v)
        print('RDB$SQL.EXPLAIN() output:')
        print('\n'.join(sql_explain_lines))

        print('Table data:')

        # show all data as DML commands 'INSERT INTO TEST(...) VALUES(...);' for possible investigation:
        t_data = []
        with act.db.connect() as con:
            cur = con.cursor()
            cur.execute('select * from test')
            cur_cols = cur.description
            ins_columns_lst = ','.join( [f[0] for f in cur_cols] )
            for r in cur:
                cur_vals = ','.join( [ str(r[i]) if r[i] else 'null' for i in range(len(cur_cols))] )
                t_data.append( f'insert into test({ins_columns_lst}) values({cur_vals});' )

        for p in t_data:
            print(p)
    act.expected_stdout = f"""
        {EXPECTED_MSG}
    """
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
