#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/8926
TITLE:       Indexes may not be used for multiple ORed conditions containing both field and non-field references
DESCRIPTION:
NOTES:
    [11.03.2026] pzotov
    Issue has been fixed:
    * in 6.x (05-mar-2026 1033):
        https://github.com/FirebirdSQL/firebird/commit/46797abad315d137290aff14c15f7b84e1020c06
    * in 5.x (05-mar-2026 1015):
        https://github.com/FirebirdSQL/firebird/commit/20400713323ebb6951e595ffd3c944de5f167b5a
    * in 4.x (05-mar-2026 1024):
        https://github.com/FirebirdSQL/firebird/commit/4e4a869bd67534bc454f4d4a38b46130b4aceed2
    * in 3.x (05-mar-2026 1030):
        https://github.com/FirebirdSQL/firebird/commit/a916ea78d1f11fbd00d8e3d0d1841cb4e46e46c8

    Thanks to dimitr for suggestion related to test implementation details.
    Confirmed problem on 5.0.4.1780-8824b2e
    Checked on: 6.0.0.1816-0c91d1a; 5.0.4.1780-0-2040071; 4.0.7.3256; 3.0.14.33845.
"""
import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    recreate table id_types(
        id int
       ,id_type int
       ,id_value int
       ,id_code int
    );

    recreate table id_life(
        id int generated by default as identity constraint pk_id_life primary key
       ,id_ident int
       ,current_state int
    );

    set term ^;
    execute block as
        declare n int  =  1000;
        declare m int  =  100;
        declare i int;
        declare v_parent_id int;
    begin
        while (n > 0) do
        begin
            insert into id_types(
                id
               ,id_type
               ,id_value
               ,id_code
            ) values (
                :n
               ,rand() * 10
               ,rand() * 10000
               ,rand() * 1000000
            ) returning id into v_parent_id
            ;

            i = 0;
            while (i < m) do
            begin
                insert into id_life(
                    id_ident
                   ,current_state
                ) values (
                    :v_parent_id
                   ,iif(rand() < 0.5, null, rand() * 5)
                );
                i = i + 1;
            end
            n = n - 1;
        end
    end
    ^
    set term ;^
    commit;

    -- ::: NB ::: This index in mandatory and must be created BEFORE others!
    -- See letter from dimitr, 11.03.2026 1519.
    create index id_types_type on id_types(id_type);
    -- ---------------------------------------------
    create index id_types_value on id_types(id_value);
    create index id_types_code on id_types(id_code);
    create index id_life_ident on id_life(id_ident);
    commit;

    set planonly;

    select first 1
        i.id, i.id_type
    from id_types i
    left join id_life l on l.id_ident = i.id
    where (i.id_value = ? or i.id_code = ?) and (i.id_type = ? or ? = 0)
    order by l.current_state nulls last, i.id_type desc
    ;
"""

substitutions = [('[ \t]+', ' ')]
act = isql_act('db', test_script, substitutions = substitutions)

@pytest.mark.version('>=3.0.14')
def test_1(act: Action):
    expected_stdout_5x = """
        PLAN SORT (JOIN (I INDEX (ID_TYPES_VALUE, ID_TYPES_CODE), L INDEX (ID_LIFE_IDENT)))
    """
    expected_stdout_6x = """
        PLAN SORT (JOIN ("I" INDEX ("PUBLIC"."ID_TYPES_VALUE", "PUBLIC"."ID_TYPES_CODE"), "L" INDEX ("PUBLIC"."ID_LIFE_IDENT")))
    """

    act.expected_stdout = expected_stdout_5x if act.is_version('<6') else expected_stdout_6x
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
