#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/8794
TITLE:       Called procedure parameter changes during execution without assignment when deleting from updatable view
DESCRIPTION:
NOTES:
    [01.11.2025] pzotov
    On 6.x bug was fixed 07.05.2025 since 6.0.0.778-d735e65 and can not be preproduced on recent snapshots
    (commit #11d5d592, "Fix for #8082 by making engine to use user buffers directly (#8145)")

    Confirmed bug on 6.0.0.776-007cd03; 5.0.4.1725-85ed111
    Checked on 6.0.0.1335-eceaf06; 5.0.4.1725-17610be; 4.0.7.3237-c6d4331; 3.0.14.33827-93a8023.
"""

import pytest
from firebird.qa import *

db = db_factory(charset='UTF8')

test_script = """
    set bail on;
    set heading off;
    set term ^;
    execute block as
    begin
        rdb$set_context('USER_SESSION', 'NUM_VALUE', '1');
        rdb$set_context('USER_SESSION', 'TXT_VALUE', 'W');
    end
    ^
    set term ^;


    create table test (
        id int generated by default as identity
        ,xnum  int
        ,xtxt  varchar(1)
    );

    create view v_test as
    select xnum, xtxt from test;


    insert into test (xnum, xtxt ) values (
         rdb$get_context('USER_SESSION', 'NUM_VALUE')
        ,rdb$get_context('USER_SESSION', 'TXT_VALUE')
    )
    ;
    commit;


    set term ^ ;
    create trigger v_test_biud for v_test active before insert or update or delete position 32767 as
    begin
        -- nop --
    end
    ^

    create procedure sp_test (
        a_num integer,
        a_txt varchar(30))
    returns (
        result_msg varchar(110)
    ) as
        declare xnum_selected_at_p1 integer;
        declare xnum_selected_at_p3 integer;
        declare xnum_from_table integer;
    begin
        result_msg = 'point-0: '
          ||   'a_num: ' || coalesce(:a_num, 'null')
          || ', a_txt: ' || coalesce(:a_txt, 'null')
          || ' -- before select from VIEW'
        ;
        suspend;

        select first 1 xnum
        from v_test
        where (xnum = :a_num) and
              (xtxt = :a_txt)
        into xnum_selected_at_p1;

        result_msg = 'point-1: '
          ||   'a_num: ' || coalesce(:a_num, 'null')
          || ', a_txt: ' || coalesce(:a_txt, 'null')
          || ' -- after select first 1 xnum from VIEW, result: xnum_selected_at_p1 = ' || coalesce(xnum_selected_at_p1, 'null')
        ;
        suspend;

        delete from v_test
        where (xnum = :a_num) and
              (xtxt = :a_txt);

        result_msg = 'point-2: '
          ||   'a_num: ' || coalesce(:a_num, 'null')
          || ', a_txt: ' || coalesce(:a_txt, 'null')
          || ' -- after delete from VIEW, result: row_count = ' || row_count
        ;
        suspend;

        select first 1 xnum
        from v_test
        where (xnum = :a_num) and
              (xtxt = :a_txt)
        into xnum_selected_at_p3;

        result_msg = 'point-3: '
          ||   'a_num: ' || coalesce(:a_num, 'null')
          || ', a_txt: ' || coalesce(:a_txt, 'null')
          || ' -- select first 1 xnum from VIEW, result: xnum_selected_at_p3 = ' || coalesce(xnum_selected_at_p3, 'null')
        ;
        suspend;

    end^

    set term ; ^

    select * from sp_test( rdb$get_context('USER_SESSION', 'NUM_VALUE'), rdb$get_context('USER_SESSION', 'TXT_VALUE'));
    commit;
"""

substitutions = [('[ \t]+', ' ')]
act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    point-0: a_num: 1, a_txt: W -- before select from VIEW
    point-1: a_num: 1, a_txt: W -- after select first 1 xnum from VIEW, result: xnum_selected_at_p1 = 1
    point-2: a_num: 1, a_txt: W -- after delete from VIEW, result: row_count = 1
    point-3: a_num: 1, a_txt: W -- select first 1 xnum from VIEW, result: xnum_selected_at_p3 = 1
"""

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout

