#coding:utf-8

"""
ID:          issue-8665
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/8665
TITLE:       SHOW DEPENDENCIES command terminates unexpectedly if there are packages in the dependencies
NOTES:
    [23.07.2025] pzotov
    Confirmed ISQL crash on 6.0.0.1052-2279f7b.
    Checked on 6.0.0.1052-c6658eb; 5.0.3.1684; 4.0.6.3222; 3.0.13.33818
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    create table test (
      id bigint generated by default as identity,
      a int,
      constraint pk_test primary key(id)
    );

    set term ^ ;

    create or alter package pkg_test
    as
    begin
      function get_a(id bigint) returns int;
    end^

    recreate package body pkg_test
    as
    begin
      function get_a(id bigint) returns int
      as
      begin
        return (select a from test where id = :id);
      end
    end^

    set term ; ^
    commit;

    show depen test;
"""

act = isql_act('db', test_script, substitutions = [(r'\+\+\+.*', '')])

expected_stdout_5x = """
    PKG_TEST:Package body->A, PKG_TEST:Package body->ID, PKG_TEST:Package body
    [TEST:Table]
"""

expected_stdout_6x = """
    PUBLIC.PKG_TEST:Package body->A, PUBLIC.PKG_TEST:Package body->ID, PUBLIC.PKG_TEST:Package body
    [PUBLIC.TEST:Table]
"""


@pytest.mark.version('>=3.0.13')
def test_1(act: Action):
    expected_stdout = expected_stdout_5x if act.is_version('<6') else expected_stdout_6x
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
