#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/9156
TITLE:       Explicit PLAN rejected with "index ... cannot be used in the specified plan" when the query contains a LEFT OUTER JOIN (regression from 3.0)
DESCRIPTION:
    [29.09.2026] zcode.ai
    Original script to reproduce problem: https://github.com/user-attachments/files/32371835/fb5_plan_leftjoin_repro.sql
    An explicit PLAN that is accepted by Firebird 3.0 was rejected by Firebird 5x and 6x with:
        index PK_T_DEFDOK cannot be used in the specified plan
    The rejected index is the primary key of T_DEFDOK, a small lookup table joined with a plain
    INNER JOIN. The trigger is an unrelated LEFT OUTER JOIN to another table (T_POZSPRZ) further
    down the query: replacing that outer join with an inner join makes the very same plan
    acceptable again, with everything else unchanged.

    Seven cases are checked (see 'qry_map'):
        T1: explicit PLAN + LEFT OUTER JOIN + 'PS.ID_NAGLCZYM IS NULL' in WHERE  => WAS FAILED
        T2: same as T1 but 'IS NULL' predicate removed from WHERE                => WAS FAILED
        T3: same as T1 but LEFT OUTER JOIN replaced with INNER JOIN              => works
        T4: same as T1 but 'PS INDEX(...)' replaced with 'PS NATURAL'            => WAS FAILED
        T5: same as T1 but flat plan instead of the nested one                   => WAS FAILED
        T6: same as T1 but GROUP BY removed, so no SORT in the plan              => works
        T7: no PLAN is forced (query T1 without explicit plan), explained plan
            that is chosen by the optimizer is printed

    Test verifies that each query is PREPARED successfully (plan validation occurs exactly at
    prepare stage), queries are NOT executed. For every case we print its comment and explained
    (detailed) plan; if DatabaseError is raised then its message and GDS codes are printed.
NOTES:
    [29.09.2026] pzotov
    DDL, DML and most of comments have been taken from the ticket.
    The origin numbers of records cause significant time for execution (more than 40s), so it was decided to reduce it in each table for same value,
    see `COUNT_REDUCTION` delimiter (it must be positive integer).
    This reduction caused CHANGES in explained plans for 3x ... 5x (but not in 6x), though the outcomes per se ('PASS' vs 'FAIL') remain the same.
    Queries and comments/explanations to be displayed in expected_out are stored in 'qry_map' dict.
    Description was generated by AI. Test itself has been implemented in the 'manual way' (not using AI).

    Confirmed bug on 6.0.0.2181; 5.0.5.1886.
    Checked on 6.0.0.2187; 5.0.5.1895; 4.0.8.3320; 3.0.15.33889.
"""

import pytest
from firebird.qa import *
from firebird.driver import DatabaseError

init_script = """
    set bail on;

    create table t_defdok (
        id_defdok    integer not null,
        id_rodzajdok integer
    );

    create table t_nagl (
        id_nagl   integer not null,
        id_defdok integer not null,
        status    smallint
    );

    create table t_poz (
        id_poz       integer not null,
        id_nagl      integer not null,
        id_kartoteka integer,
        id_magazyn   integer,
        datadok      timestamp,
        ilosc        numeric(15,4)
    );


    -- the leading segment of the primary key is the low-selectivity column,
    -- exactly as in the production schema.
    create table t_pozsprz (
        rodzsprzpoz smallint not null,
        id_pozco    integer  not null,
        id_pozczym  integer  not null,
        id_naglczym integer
    );

    commit;

    --   Volumes matter: the optimizer must be pushed into the cost regime where it
    --   would choose a hash join for the T_DEFDOK lookup table. With much smaller
    --   volumes the explicit plan is accepted and nothing is reproduced.
    set term ^ ;
    execute block as
        -- These values are specified in the ticket:
        declare T_DEFDOK_CNT int = 498;
        declare T_NAGL_CNT int = 200000;
        declare T_POZ_CNT int = 5000000;
        declare T_POZSPRZ_CNT int = 2000000;
        declare i int;

        -- #########################
        -- ###   D I V I S O R   ###
        -- #########################
        -- Use integer number >= 1 in order to reduce total count of records
        -- but with preserving the RATIOS between them (per tables):
        declare COUNT_REDUCTION int = 50;
    begin

        T_DEFDOK_CNT = T_DEFDOK_CNT / COUNT_REDUCTION;
        T_NAGL_CNT  = T_NAGL_CNT / COUNT_REDUCTION;
        T_POZ_CNT = T_POZ_CNT / COUNT_REDUCTION;
        T_POZSPRZ_CNT = T_POZSPRZ_CNT / COUNT_REDUCTION;

        i = 0;
        while (i < T_DEFDOK_CNT) do
        begin
            insert into t_defdok (id_defdok, id_rodzajdok) values (:i, mod(:i, 30));
            i = i + 1;
        end

        i = 0;
        while (i < T_NAGL_CNT) do
        begin
            insert into t_nagl (id_nagl, id_defdok, status)
            values (:i, mod(:i, 498), 0);
            i = i + 1;
        end

        i = 0;
        while (i < T_POZ_CNT) do
        begin
            insert into t_poz (id_poz, id_nagl, id_kartoteka, id_magazyn, datadok, ilosc)
            values (:i, mod(:i, :T_NAGL_CNT), mod(:i, 5000), 10046,
                    dateadd(mod(:i, 400) day to timestamp '2025-12-01'), 1);
            i = i + 1;
        end

        i = 0;
        while (i < T_POZSPRZ_CNT) do
        begin
            -- Partial coverage is intentional: part of T_POZ has a matching row in
            -- T_POZSPRZ, part has none, and both values of the leading key segment
            -- are present.

            if (mod(i, 3) = 0) then
              insert into t_pozsprz (rodzsprzpoz, id_pozco, id_pozczym, id_naglczym)
              values (2, :i, :i, mod(:i, :T_NAGL_CNT));

            if (mod(i, 7) = 0) then
              insert into t_pozsprz (rodzsprzpoz, id_pozco, id_pozczym, id_naglczym)
              values (1, :i, :i, mod(:i, :T_NAGL_CNT));

            i = i + 1;
        end

    end^
    set term ; ^
    commit;

    alter table t_defdok add constraint pk_t_defdok primary key (id_defdok);
    alter table t_nagl add constraint pk_t_nagl primary key (id_nagl);
    alter table t_poz add constraint pk_t_poz primary key (id_poz);
    alter table t_pozsprz add constraint pk_t_pozsprz primary key (rodzsprzpoz, id_pozco, id_pozczym);

    create index idx_nagl_defdok on t_nagl (id_defdok);
    create index idx_poz_datadok   on t_poz (datadok);
    create index idx_poz_nagl      on t_poz (id_nagl);
    create index idx_poz_magazyn   on t_poz (id_magazyn);
    create index idx_poz_kartoteka on t_poz (id_kartoteka);
    commit;
"""
db = db_factory(init = init_script)

qry_map = {
    1000 :
    (
        """
            select p.id_kartoteka, sum(p.ilosc)
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            left outer join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where
                (n.status = 0)
                and (p.id_magazyn = 10046)
                and (p.datadok >= timestamp '2026-02-06')
                and (p.datadok <  timestamp '2026-09-01')
                and (ps.id_naglczym is null) ------------------------------------ `IS NULL` here
                and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            group by p.id_kartoteka
            plan sort (join (join (p index (idx_poz_datadok, idx_poz_magazyn),
                                   n index (pk_t_nagl),
                                   d index (pk_t_defdok)),
                             ps index (pk_t_pozsprz)))
        """
        ,
        """
            Failed before fix with "index PK_T_DEFDOK cannot be used in the specified plan"
        """
    )
    ,
    2000 :
    (
        """
            select p.id_kartoteka, sum(p.ilosc)
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            LEFT OUTER ------------------------------------------------------------ `OUTER JOIN` here
            join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where
                (n.status = 0)
                and (p.id_magazyn = 10046)
                and (p.datadok >= timestamp '2026-02-06')
                and (p.datadok <  timestamp '2026-09-01')
                ------------------------------------------------------------------- no `IS NULL` here
                and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            group by p.id_kartoteka
            plan sort (join (join (p index (idx_poz_datadok, idx_poz_magazyn),
                                   n index (pk_t_nagl),
                                   d index (pk_t_defdok)),
                             ps index (pk_t_pozsprz)));

        """
        ,
        """
            The `IS NULL` predicate was removed from outer-joined table but this query failed before as well.
        """
    )

    ,
    3000 :
    (
        """
            select p.id_kartoteka, sum(p.ilosc)
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            INNER ---------------------------------------------------------------- `INNER JOIN` here
            join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where
                (n.status = 0)
                and (p.id_magazyn = 10046)
                and (p.datadok >= timestamp '2026-02-06')
                and (p.datadok <  timestamp '2026-09-01')
                and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            group by p.id_kartoteka
            plan sort (join (join (p index (idx_poz_datadok, idx_poz_magazyn),
                                   n index (pk_t_nagl),
                                   d index (pk_t_defdok)),
                             ps index (pk_t_pozsprz)))
        """
        ,
        """
            Passed. Same query as qry_map[2000], INNER instead of LEFT JOIN. This isolates the outer join as place where problem occurs.
        """
    )
    ,
    4000 :
    (
        """
            select p.id_kartoteka, sum(p.ilosc)
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            left outer join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where
                (n.status = 0)
                and (p.id_magazyn = 10046)
                and (p.datadok >= timestamp '2026-02-06')
                and (p.datadok <  timestamp '2026-09-01')
                and (ps.id_naglczym is null)
                and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            group by p.id_kartoteka
            plan sort (join (join (p index (idx_poz_datadok, idx_poz_magazyn),
                                   n index (pk_t_nagl),
                                   d index (pk_t_defdok)),
                             PS NATURAL))
        """
        ,
        """
            FAILS as well: T1 with `PS NATURAL`. No matter how the outer-joined stream is read: its presence makes the `D` index unusable
       """
    )
    ,
    5000 :
    (
        """
            select p.id_kartoteka, sum(p.ilosc)
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            left outer join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where
                (n.status = 0)
                and (p.id_magazyn = 10046)
                and (p.datadok >= timestamp '2026-02-06')
                and (p.datadok <  timestamp '2026-09-01')
                and (ps.id_naglczym is null)
                and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            group by p.id_kartoteka
            plan sort (join (p index (idx_poz_datadok, idx_poz_magazyn),
                             n index (pk_t_nagl),
                             d index (pk_t_defdok),
                             ps index (pk_t_pozsprz)))
        """
        ,
        """
             Failed if query was qry_map[1000] but with a flat plan instead of the nested one.
        """
    )
    ,
    6000 :
    (
        """
            select first 100 p.id_kartoteka, p.ilosc
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            left outer join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where
                (n.status = 0)
                and (p.id_magazyn = 10046)
                and (p.datadok >= timestamp '2026-02-06')
                and (p.datadok <  timestamp '2026-09-01')
                and (ps.id_naglczym is null)
                and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            plan join (join (p index (idx_poz_datadok, idx_poz_magazyn),
                             n index (pk_t_nagl),
                             d index (pk_t_defdok)),
                       ps index (pk_t_pozsprz))
        """
        ,
        """
             Passed if query was qry_map[1000] without group by so without sort in the plan.
        """

    )
    ,
    7000 :
    (
        """
            select p.id_kartoteka, sum(p.ilosc)
            from t_poz p
            join t_nagl n   on (p.id_nagl = n.id_nagl)
            join t_defdok d on (n.id_defdok = d.id_defdok)
            left outer join t_pozsprz ps on (p.id_poz = ps.id_pozco) and (ps.rodzsprzpoz = 2)
            where (n.status = 0)
              and (p.id_magazyn = 10046)
              and (p.datadok >= timestamp '2026-02-06')
              and (p.datadok <  timestamp '2026-09-01')
              and (ps.id_naglczym is null)
              and (d.id_rodzajdok <> 20) and (d.id_rodzajdok <> 22)
            group by p.id_kartoteka
        """
        ,
        """
            The plan chosen by the engine when no plan is forced (i.e. qry_map[1000] without plan)
        """
    )
}

substitutions = [('record length.*', ''), ('key length.*', '')]
act = python_act('db', substitutions = substitutions)

#-----------------------------------------------------------

@pytest.mark.version('>=3.0')
def test_1(act: Action, capsys):
    with act.db.connect() as con:
        cur = con.cursor()
        for qry_idx, qry_data in qry_map.items():
            test_sql, qry_comment = qry_data[:2]
            print(qry_comment)
            ps, rs =  None, None
            try:
                cur = con.cursor()
                ps = cur.prepare(test_sql)
                # Print explained plan with padding eash line by dots in order to see indentations:
                print( '\n'.join([replace_leading(s) for s in ps.detailed_plan.split('\n')]) )
            except DatabaseError as e:
                print(e.__str__())
                print(e.gds_codes)
            finally:
                if rs:
                    rs.close() # <<< EXPLICITLY CLOSING CURSOR RESULTS
                if ps:
                    ps.free()

    expected_out_3x = f"""
        {qry_map.get(1000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(2000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(3000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Sort (record length: 148, key length: 8)
        ............-> Filter
        ................-> Hash Join (inner)
        ....................-> Filter
        ........................-> Table "T_POZSPRZ" as "PS" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 1/3)
        ....................-> Record Buffer (record length: 115)
        ........................-> Nested Loop Join (inner)
        ............................-> Filter
        ................................-> Table "T_POZ" as "P" Access By ID
        ....................................-> Bitmap And
        ........................................-> Bitmap
        ............................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ........................................-> Bitmap
        ............................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ............................-> Filter
        ................................-> Table "T_NAGL" as "N" Access By ID
        ....................................-> Bitmap
        ........................................-> Index "PK_T_NAGL" Unique Scan
        ............................-> Filter
        ................................-> Table "T_DEFDOK" as "D" Access By ID
        ....................................-> Bitmap
        ........................................-> Index "PK_T_DEFDOK" Unique Scan
        
        {qry_map.get(4000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Filter
        ........................-> Table "T_POZSPRZ" as "PS" Full Scan

        {qry_map.get(5000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)
        
        {qry_map.get(6000)[1]}
        Select Expression
        ....-> First N Records
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Nested Loop Join (inner)
        ....................-> Filter
        ........................-> Table "T_POZ" as "P" Access By ID
        ............................-> Bitmap And
        ................................-> Bitmap
        ....................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................................-> Bitmap
        ....................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ....................-> Filter
        ........................-> Table "T_NAGL" as "N" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_NAGL" Unique Scan
        ....................-> Filter
        ........................-> Table "T_DEFDOK" as "D" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)
        
        {qry_map.get(7000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Full Scan
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "IDX_NAGL_DEFDOK" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_NAGL" Range Scan (full match)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)
    """

    expected_out_5x = f"""
        {qry_map.get(1000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(2000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Nested Loop Join (outer)
        ............-> Sort (record length: 124, key length: 8)
        ................-> Nested Loop Join (inner)
        ....................-> Filter
        ........................-> Table "T_POZ" as "P" Access By ID
        ............................-> Bitmap And
        ................................-> Bitmap
        ....................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................................-> Bitmap
        ....................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ....................-> Filter
        ........................-> Table "T_NAGL" as "N" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_NAGL" Unique Scan
        ....................-> Filter
        ........................-> Table "T_DEFDOK" as "D" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_DEFDOK" Unique Scan
        ............-> Filter
        ................-> Table "T_POZSPRZ" as "PS" Access By ID
        ....................-> Bitmap
        ........................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(3000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Sort (record length: 148, key length: 8)
        ............-> Filter
        ................-> Hash Join (inner)
        ....................-> Filter
        ........................-> Table "T_POZSPRZ" as "PS" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 1/3)
        ....................-> Record Buffer (record length: 115)
        ........................-> Nested Loop Join (inner)
        ............................-> Filter
        ................................-> Table "T_POZ" as "P" Access By ID
        ....................................-> Bitmap And
        ........................................-> Bitmap
        ............................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ........................................-> Bitmap
        ............................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ............................-> Filter
        ................................-> Table "T_NAGL" as "N" Access By ID
        ....................................-> Bitmap
        ........................................-> Index "PK_T_NAGL" Unique Scan
        ............................-> Filter
        ................................-> Table "T_DEFDOK" as "D" Access By ID
        ....................................-> Bitmap
        ........................................-> Index "PK_T_DEFDOK" Unique Scan
        
        {qry_map.get(4000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Filter
        ........................-> Table "T_POZSPRZ" as "PS" Full Scan

        {qry_map.get(5000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)
        
        {qry_map.get(6000)[1]}
        Select Expression
        ....-> First N Records
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Nested Loop Join (inner)
        ....................-> Filter
        ........................-> Table "T_POZ" as "P" Access By ID
        ............................-> Bitmap And
        ................................-> Bitmap
        ....................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................................-> Bitmap
        ....................................-> Index "IDX_POZ_MAGAZYN" Range Scan (full match)
        ....................-> Filter
        ........................-> Table "T_NAGL" as "N" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_NAGL" Unique Scan
        ....................-> Filter
        ........................-> Table "T_DEFDOK" as "D" Access By ID
        ............................-> Bitmap
        ................................-> Index "PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)
        
        {qry_map.get(7000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "T_DEFDOK" as "D" Full Scan
        ........................-> Filter
        ............................-> Table "T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "IDX_NAGL_DEFDOK" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_NAGL" Range Scan (full match)
        ....................................-> Bitmap
        ........................................-> Index "IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................-> Filter
        ....................-> Table "T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PK_T_POZSPRZ" Range Scan (partial match: 2/3)
    """

    expected_out_6x = f"""
        {qry_map.get(1000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PUBLIC"."PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(2000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Nested Loop Join (outer)
        ............-> Sort (record length: 124, key length: 8)
        ................-> Nested Loop Join (inner)
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ............................-> Bitmap And
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."IDX_POZ_MAGAZYN" Range Scan (full match)
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ............................-> Bitmap
        ................................-> Index "PUBLIC"."PK_T_NAGL" Unique Scan
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_DEFDOK" as "D" Access By ID
        ............................-> Bitmap
        ................................-> Index "PUBLIC"."PK_T_DEFDOK" Unique Scan
        ............-> Filter
        ................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Access By ID
        ....................-> Bitmap
        ........................-> Index "PUBLIC"."PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(3000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Sort (record length: 148, key length: 8)
        ............-> Filter
        ................-> Hash Join (inner) (keys: 1, total key length: 4)
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Access By ID
        ............................-> Bitmap
        ................................-> Index "PUBLIC"."PK_T_POZSPRZ" Range Scan (partial match: 1/3)
        ....................-> Record Buffer (record length: 115)
        ........................-> Nested Loop Join (inner)
        ............................-> Filter
        ................................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ....................................-> Bitmap And
        ........................................-> Bitmap
        ............................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ........................................-> Bitmap
        ............................................-> Index "PUBLIC"."IDX_POZ_MAGAZYN" Range Scan (full match)
        ............................-> Filter
        ................................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."PK_T_NAGL" Unique Scan
        ............................-> Filter
        ................................-> Table "PUBLIC"."T_DEFDOK" as "D" Access By ID
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."PK_T_DEFDOK" Unique Scan

        {qry_map.get(4000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Full Scan

        {qry_map.get(5000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_MAGAZYN" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."PK_T_NAGL" Unique Scan
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_DEFDOK" as "D" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PUBLIC"."PK_T_POZSPRZ" Range Scan (partial match: 2/3)
        
        {qry_map.get(6000)[1]}
        Select Expression
        ....-> First N Records
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Nested Loop Join (inner)
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ............................-> Bitmap And
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."IDX_POZ_MAGAZYN" Range Scan (full match)
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ............................-> Bitmap
        ................................-> Index "PUBLIC"."PK_T_NAGL" Unique Scan
        ....................-> Filter
        ........................-> Table "PUBLIC"."T_DEFDOK" as "D" Access By ID
        ............................-> Bitmap
        ................................-> Index "PUBLIC"."PK_T_DEFDOK" Unique Scan
        ................-> Filter
        ....................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PUBLIC"."PK_T_POZSPRZ" Range Scan (partial match: 2/3)

        {qry_map.get(7000)[1]}
        Select Expression
        ....-> Aggregate
        ........-> Filter
        ............-> Nested Loop Join (outer)
        ................-> Sort (record length: 124, key length: 8)
        ....................-> Nested Loop Join (inner)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_DEFDOK" as "D" Full Scan
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_NAGL" as "N" Access By ID
        ................................-> Bitmap
        ....................................-> Index "PUBLIC"."IDX_NAGL_DEFDOK" Range Scan (full match)
        ........................-> Filter
        ............................-> Table "PUBLIC"."T_POZ" as "P" Access By ID
        ................................-> Bitmap And
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_NAGL" Range Scan (full match)
        ....................................-> Bitmap
        ........................................-> Index "PUBLIC"."IDX_POZ_DATADOK" Range Scan (lower bound: 1/1, upper bound: 1/1)
        ................-> Filter
        ....................-> Table "PUBLIC"."T_POZSPRZ" as "PS" Access By ID
        ........................-> Bitmap
        ............................-> Index "PUBLIC"."PK_T_POZSPRZ" Range Scan (partial match: 2/3)
    """

    act.expected_stdout = expected_out_3x if act.is_version('<5') else expected_out_5x if act.is_version('<6') else expected_out_6x
    act.stdout = capsys.readouterr().out
    assert act.clean_stdout == act.clean_expected_stdout
