#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/pull/9108
TITLE:       Convert string literals to the operand type at prepare time in comparisons
DESCRIPTION:
    Test creates table with fields of datatypes psecified in the ticket: double, decfloat(16/34), int128, date, time[with TZ], timestamp[with TZ]
    Then it adds <TEST_ROWS_CNT> into it with random not-null data.
    At some iteration (random, from scope 1...TEST_ROWS_CNT) generated values are saved also in auxiliary table (AUX_DATA).
    These values will be used further as LITERALS and EXECUTE STATEMENT PARAMETERS in the queries that will be checked.
    For example, following queries will use same timestamp with TZ as literal and parameter:
       Q1: select count(*) from test  where tstz is not distinct from '2026-08-19 05:35:40.0000 Asia/Urumqi'
       Q2: execute block returns(cnt int) as begin execute statement ('select count(*) from test where tstz is not distinct from ?') ('2026-08-19 05:35:40.0000 Asia/Urumqi') into cnt; suspend; end
    Test will compare values returned by Q1 and Q2: they must be equal.
    Check is repeated for cases when table has no indices and then when each column is indexed using regular, partial and computed index -- see func 'add_indices'.
NOTES:
    [14.08.2026] pzotov
    Performance slowdown detected for some cases, see: https://github.com/FirebirdSQL/firebird/pull/9108#issuecomment-5276992625
    Test may be supplemented later with measurement of CPU cycles for each performing pair of queries and comparing their ratio with some threshold.
    Checked on 6.0.0.2143-81cfcf9.
"""

import random
import pytest
from firebird.qa import *

####################
TEST_ROWS_CNT = 1000
####################

init_script = f"""
    create exception exc_wrong_random_value_chosen 'Random value @1 does not belong to the scope [@2 ... @3]. Check algorithm.';
    set autoterm on;
    create domain dm_tz_name varchar(63) character set utf8;
    recreate table test(
        id int generated by default as identity constraint pk_test primary key
        ,dbl  double precision
        ,df16 decfloat(16)
        ,df34 decfloat(34)
        ,i128 int128
        ,dt   date
        ,tm   time
        ,tmtz time with time zone
        ,ts   timestamp
        ,tstz timestamp with time zone
    );
    recreate table aux_data(
        rnd_dbl double precision
        ,rnd_df16 decfloat(16)
        ,rnd_df34 decfloat(34)
        ,rnd_i128 int128
        ,rnd_dt   varchar(10)
        ,rnd_tm   varchar(13)
        ,rnd_tmtz varchar(128)
        ,rnd_ts   varchar(24)
        ,rnd_tstz varchar(128)
        ,rnd_tz_id int
        ,rnd_tz_name dm_tz_name
    );

    -- obtain random time zone and store it in aux_data:
    execute block as
        declare v_min_tz int;
        declare v_max_tz int;
        declare v_rnd_x double precision;
        declare v_rnd_tz_id int;
        declare v_rnd_tz_name dm_tz_name;
    begin
        select min(z.rdb$time_zone_id), max(z.rdb$time_zone_id)
        from rdb$time_zones z
        into v_min_tz, v_max_tz;

        v_rnd_x = v_min_tz - 0.5 + rand() * (v_max_tz - v_min_tz + 0.5);
        v_rnd_tz_id = -2147483648;
        select z.rdb$time_zone_id, z.rdb$time_zone_name
        from rdb$time_zones z
        where z.rdb$time_zone_id >= :v_rnd_x
        order by z.rdb$time_zone_id rows 1
        into v_rnd_tz_id, v_rnd_tz_name;
        if ( not v_rnd_tz_id between v_min_tz and v_max_tz ) then
        begin
            exception exc_wrong_random_value_chosen using(v_rnd_tz_id, v_min_tz,v_max_tz);
        end
        insert into aux_data(rnd_tz_id, rnd_tz_name) values(:v_rnd_tz_id, :v_rnd_tz_name);
    end;
    commit;

    -- fill test table:
    execute block as
        declare n_rows int = {TEST_ROWS_CNT};
        declare v_rnd_tz_name dm_tz_name;
        declare v_i128_min int128 = -170141183460469231731687303715884105728;
        declare v_i128_max int128 = 170141183460469231731687303715884105727;
        declare v_i128_rnd int128;
        declare id_rand int;
        declare v_id int;
    begin
        select rnd_tz_name from aux_data into v_rnd_tz_name;
        id_rand = maxvalue(1, rand() * n_rows);
        while (n_rows > 0) do
        begin
            v_i128_rnd = iif(rand() <0.5, rand()*v_i128_max, rand()*v_i128_min);
            insert into test(
                 dbl
                ,df16
                ,df34
                ,i128
                ,dt
                ,tm
                ,tmtz
                ,ts
                ,tstz
            ) values (
                 rand()
                ,iif(rand() < 0.1, -9.999999999999999E384, iif(rand() < 0.2, 9.999999999999999E384, rand() * 9.999999999999999E384 ) )
                ,iif(rand() < 0.1, -9.999999999999999999999999999999999E6144, iif(rand() < 0.2, 9.999999999999999999999999999999999E6144, rand() * 9.999999999999999999999999999999999E6144 ) )
                ,iif(rand() < 0.1, :v_i128_max, iif(rand() < 0.2, :v_i128_min, :v_i128_rnd) )
                ,iif(rand() < 0.5, current_date-2, current_date+2) -- avoid usage of dates from [YESTERDAY-1 ... TOMORROW+1] because date may change during this test!
                ,dateadd( rand() * 86400 second to time '00:00:00' ) -- time
                ,cast(dateadd( rand() * 86400 second to time '00:00:00' ) as varchar(13)) || ' ' || :v_rnd_tz_name -- time with time zone
                ,cast( iif(rand() < 0.5, current_date-2, current_date+2) as varchar(10)) || ' ' || cast(dateadd( rand() * 86400 second to time '00:00:00' ) as varchar(13))
                ,cast( iif(rand() < 0.5, current_date-2, current_date+2) as varchar(10)) || ' ' || cast(dateadd( rand() * 86400 second to time '00:00:00' ) as varchar(13)) || ' ' || :v_rnd_tz_name
            )
            returning id into v_id
            ;
            if (id_rand = n_rows) then
            begin
                merge into aux_data t
                using (
                    select dbl, df16, df34, i128, dt, tm, tmtz, ts, tstz
                    from test
                    where id = :v_id
                ) s on 1=1
                when MATCHED then
                    update set
                        rnd_dbl  = s.dbl
                       ,rnd_df16 = s.df16
                       ,rnd_df34 = s.df34
                       ,rnd_i128 = s.i128
                       ,rnd_dt   = s.dt
                       ,rnd_tm   = s.tm
                       ,rnd_tmtz = s.tmtz
                       ,rnd_ts   = s.ts
                       ,rnd_tstz = s.tstz
                ;
                    
            end
            n_rows = n_rows - 1;
        end

        insert into test(
             dbl
            ,df16
            ,df34
            ,i128
            ,dt
            ,tm
            ,tmtz
            ,ts
            ,tstz
        ) values (
             null
            ,null
            ,null
            ,null
            ,null
            ,null
            ,null
            ,null
            ,null
        );
    end;
    commit;
"""
db = db_factory(filename = 'gh_9108_tmp.fdb', init = init_script) # , do_not_drop = True)
act = python_act('db')

#-------------------------------------------------------

def add_indices(mode, con):

    idx_lst = []
    sql_fields_lst = "select trim(rdb$field_name) from rdb$relation_fields rf where rf.rdb$relation_name = upper('test') and rf.rdb$field_name <> upper('id')"
    cur = con.cursor()
    cur.execute(sql_fields_lst)
    for r in cur:
        idx_direction = 'ascending' if random.random() < 0.5 else 'descending'
        idx_name = f'test_{r[0]}_{mode}_{idx_direction}'
        idx_suff = ''
        if mode == 'index_regular':
           idx_suff = f' ({r[0]})'
        elif mode == 'index_partial':
           idx_suff = f' ({r[0]}) where {r[0]} is not null'
        elif mode == 'index_computed':
           idx_suff = f' computed by ({r[0]})'

        idx_lst.append(idx_name)
        con.execute_immediate(f"create {idx_direction} index {idx_name} on test {idx_suff}")
    con.commit()

    return idx_lst

#-------------------------------------------------------


@pytest.mark.version('>=6.0')
def test_1(act: Action):

    sql_main = """
        with
        t as (
            select u.ty from unlist('dbl,df16,df34,i128,dt,tm,tmtz,ts,tstz' returning varchar) as u(ty)
        )
        ,o as (
            select u.op from unlist('= ?,> ?,>= ?,<> ?,< ?,<= ?,is not distinct from ?,is distinct from ?,between ? and ?' returning varchar) as u(op)
        )
        ,v as (
            --    select
            --        cast(pi() as double precision) dbl
            --        ,cast(9.999999999999999E384 as decfloat(16)) df16
            --        ,cast(9.999999999999999999999999999999999E6144 as decfloat(34)) df34
            --        ,cast(170141183460469231731687303715884105727 as int128) i128
            --        ,cast('15.08.2026' as date) dt
            --        ,cast('13:14:15.678' as time) tm
            --        ,cast('21:22:23.345 Indian/Cocos' as time with time zone) tmtz
            --        ,cast('15.08.2026 21:22:23.345' as timestamp) ts
            --        ,cast('15.08.2026 21:22:23.345 Indian/Cocos' as timestamp with time zone) tstz
            --    from rdb$database
            select a.rnd_dbl as dbl, a.rnd_df16 as df16, a.rnd_df34 as df34, a.rnd_i128 as i128, a.rnd_dt as dt, a.rnd_tm as tm, a.rnd_tmtz as tmtz, a.rnd_ts as ts, a.rnd_tstz as tstz
            from aux_data a

        )
        ,d as (
            -- Special literals to be compared with DATE column:
            select u.dx from unlist(q'#YESTERDAY,TODAY,TOMORROW,NOW#' returning varchar) as u(dx)
        )
        ,s1 as (
            select t.ty, o.op
            ,d.dx
            ,'where ' || trim(t.ty) || ' ' || o.op as s
            ,decode(t.ty, 'dbl', v.dbl, 'df16', v.df16, 'df34', v.df34, 'i128', v.i128, 'dt', v.dt, 'tm', v.tm, 'tmtz', v.tmtz, 'ts', v.ts, 'tstz', v.tstz) as v
            ,iif( t.ty in ('dt', 'tm', 'tmtz', 'ts', 'tstz'), q'#'#', '' ) as e
            from t
            cross join o
            cross join v
            -- TIME [WITH TZ] can not be compared with literals 'YESTERDAY', 'TODAY', 'TOMORROW'
            -- Comparison with 'NOW' may produce diff outcome for two subsequent queries (q1 and q2, see below)
            -- thus we must skip it. Only DATE and TIMESTAMP [WITH TZ] may be involved in such comparison:
            left join d on t.ty in ('dt', 'ts', 'tstz')
        )
        --select * from s1

        ,s2 as (
            select ty, op, dx, s, v, e
            ,'select count(*) from test ' || ' ' || replace(s, '?', e || iif(n.i = 1, v, dx) ||  e) as q1
            -- for 'BETWEEN ? and ?' we use SAME value for both params:
            ,q'#('select count(*) from test #' || s || q'#') (#' || e || iif( op containing 'between',  iif(n.i=1, v, dx) || e || ',' || e || iif(n.i = 1, v, dx), iif(n.i = 1, v, dx) ) || e || ')' as q2
            from s1
            join ( select i from generate_series(1, 2) as s(i) ) n on n.i = 1 or n.i = 2 and s1.dx is not null
            where
                n.i = 1
                or n.i = 2
                and (
                    ty in ('dt', 'ts', 'tstz') -- or ty in ('tm', 'tmtz') and dx  = 'NOW'
                )
        )
        select q1,q2 from s2
        -- 4debug
        -- rows 3
    """

    with act.db.connect() as con:
        cur_main = con.cursor()
        cur_chk = con.cursor()

        for mode in ('natural_reads', 'index_regular', 'index_partial', 'index_computed'):
            
            idx_lst = []
            if mode != 'natural_reads':
                idx_lst = add_indices(mode, con)

            cur_main.execute(sql_main)
            for r in cur_main:
                q1, q2 = r[:2]
                q2 = f'execute block returns(cnt int) as begin execute statement {q2} into cnt; suspend; end'

                cur_chk.execute(q1)
                cnt1 = cur_chk.fetchone()[0]

                cur_chk.execute(q2)
                cnt2 = cur_chk.fetchone()[0]

                assert cnt1 == cnt2, f'Mismatch detected between results on {mode=} for queries:\n{q1=}\n=== vs ===\n{q2=}\n{cnt1=} <> {cnt2=}'

                # 4debug only:
                #qx = f"execute block as begin /* trace_me */ rdb$set_context('USER_SESSION', 'CHK', q'#{q1}: {cnt1} {cnt2}#'); end"
                #con.execute_immediate(qx)
            con.commit()
            
            for x in idx_lst:
                con.execute_immediate(f"drop index {x}")
                con.commit()

    # If all pair of generated queries did return same number of rows then all fine.
    assert 1
