#coding:utf-8

"""
ID:          7e59041f9c
ISSUE:       https://www.sqlite.org/src/tktview/7e59041f9c
TITLE:       DISTINCT malfunctions for a VIEW
DESCRIPTION:
NOTES:
    [15.08.2025] pzotov
    Checked on 6.0.0.1204, 5.0.4.1701, 4.0.7.3231, 3.0.14.33824
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    create table t0(id int generated by default as identity, c0 int);
    create table vt0(id int generated by default as identity, c0 int);
    create view v0 as 
    select distinct t0.c0 
    from vt0 cross join t0
    order by t0.id;

    insert into t0(c0) values (1);
    insert into t0(c0) values (0);
    insert into vt0(c0) values (0);
    insert into vt0(c0) values (0);

    set count on;
    select * from v0; -- unexpected: 4 rows are fetched
"""

substitutions = [('[ \t]+', ' ')]
act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    C0 1
    C0 0
    Records affected: 2
"""

@pytest.mark.version('>=3')
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
