#coding:utf-8

"""
ID:          a696379c1f
ISSUE:       https://www.sqlite.org/src/tktview/a696379c1f
TITLE:       Access violation error trying to insert into triggered view
DESCRIPTION:
NOTES:
    [22.08.2025] pzotov
    Checked on 6.0.0.1244, 5.0.4.1701, 4.0.7.3231, 3.0.14.33824
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    create table t1(x integer generated by default as identity primary key, y int);
    create table t2(z int);
    create view v1 as select * from t2;
    set term ^;
    create trigger r1 before insert on v1 as
    begin
       insert into t1(y) values(new.z);
    end
    ^ set term ;^
    commit;
    insert into v1 values(0);

    set count on;
    select * from t1;
    select * from t2;
"""

substitutions = [('[ \t]+', ' ')]
act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    X 1
    Y 0
    Records affected: 1
    Records affected: 0
"""

@pytest.mark.version('>=3')
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
