#coding:utf-8

"""
ID:          n/a
ISSUE:       https://www.usenix.org/system/files/osdi20-rigger.pdf
TITLE:       Incorrect result for DISTINCT.
DESCRIPTION:
    https://www.usenix.org/system/files/osdi20-rigger.pdf
    page 10 listing 4

    COULD NOT REPRODUCE PROPER (EXPECTED) REQULT. SOURCE QUERY SYNTAX SEEMS WEIRD!
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    -- set list on;
    recreate table t0 (c0 int, c1 int, c2 int, c3 int /* generated by default as identity */, unique (c3 ,c2 ));
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(0);
    insert into t0 ( c2 ) values(null);
    insert into t0 ( c2 ) values(1);
    insert into t0 ( c2 ) values(0);

    update t0 set c1 = 0;
    insert into t0 ( c0 ) values (0);
    insert into t0 ( c0 ) values (0);
    insert into t0 ( c0 ) values (null);
    insert into t0 ( c0 ) values (0);

    update t0 set c2 = 1;
    select distinct * from t0 where c2 = 1;

"""

act = isql_act('db', test_script, substitutions=[('[ \t]+', ' ')])

@pytest.mark.skip("Could not reproduce expected output. Source query syntax seems weird")
@pytest.mark.version('>=3.0')
def test_1(act: Action):
    act.expected_stdout = """
    """
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
