#coding:utf-8

"""
ID:          n/a
TITLE:       WHERE CURRENT OF <C> within block that has savepoint: statement #2 must see changes produced by statement #1
DESCRIPTION:
    Original issue:
        https://quality.embarcadero.com/projects/IBP/issues/IBP-124?filter=allopenissues&orderby=priority+ASC%2C+updated+DESC
NOTES:
    [02.06.2025] pzotov
    1. Test has similar code to described in CORE-5794 (GH-6057) but adds WHEN-block in order to create implicit savepoint.
       This causes changes that have been done by statement #1 to be seen for (same) cursor when it runs statement #2.
    2. Difference of this begaviour (comparing to 2.5) relates to CURSOR STABILITY feature that appeared since 3.x
       Workaround was provided by hvlad, see:
       https://github.com/FirebirdSQL/firebird/issues/6057#issuecomment-826242377
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    create or alter procedure sp_test as begin end;
    recreate table test (
        id     int generated by default as identity,
        data1  int,
        data2  int
    );
    recreate table dml_audit(log_id int generated by default as identity, log_msg varchar(255));

    set term ^;
    create trigger trg_test_bu0 for test active before update position 0 as
      declare log_msg type of column dml_audit.log_msg;
    begin
        log_msg =
            'old.data1: ' || old.data1 ||
            ', new.data1: ' || new.data1 ||
            ', old.data2: ' || old.data2 ||
            ', new.data2: ' || new.data2
        ;
        insert into dml_audit(log_msg) values(:log_msg);
    end
    ^
    create or alter procedure sp_test as
        declare var_id integer;
    begin
        for
            select t.id from test t where t.id = 1
        into
            :var_id
        as cursor
            cur_tst
        do
        begin
            update test t set t.data1 = 1 -- ....... statement #1
            where current of cur_tst;
        
            update test t set t.data2 = 2 -- ....... statement #2
            where current of cur_tst;

        -- following 'when'-block causes engine to create implicit savepoint and
        -- changed value of data1 will be seen here.
        -- Without this block value of 'DATA1' column will be seen here as old one, i.e. 0.
        -- https://github.com/FirebirdSQL/firebird/issues/6057#issuecomment-826242377
        when any do
            exception;
        end
    end ^
    set term ;^
    commit;
    
    insert into test (data1, data2) values (0, 0);
    execute procedure sp_test;

    select * from test;
    select * from dml_audit;
"""

act = isql_act('db', test_script)

expected_stdout = """
    ID                              1
    DATA1                           1
    DATA2                           2

    LOG_ID                          1
    LOG_MSG                         old.data1: 0, new.data1: 1, old.data2: 0, new.data2: 0
    LOG_ID                          2
    LOG_MSG                         old.data1: 1, new.data1: 1, old.data2: 0, new.data2: 2
"""

@pytest.mark.version('>=3.0')
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
