#coding:utf-8

"""
ID:           n/a
ISSUE:        https://github.com/FirebirdSQL/firebird/pull/9193
TITLE:        CTAS. 'WITH DATA': data completeness for regular, global temporary and local temporary tables
DESCRIPTION:
    [text generated by zcode.ai]
    With `WITH DATA`, rows are loaded using the same bulk insert mechanism as during `gbak` restore (see
    doc/sql.extensions/README.create_table_as_query.md, section "Bulk insert", implemented by commit
    474cb872f93a11ec156ef43f57624ba9ea7f093f), and this applies to regular, global temporary and local temporary
    tables.
    Checked here:
    * completeness and correctness of the loaded data for all kinds of target tables: 10000 rows with NULLs, unicode
      varchar, text and binary blobs, boolean, numeric and timestamp with time zone; fidelity of the transfer is
      checked by joining source and target on PK with 'is distinct from' for every column;
    * lifecycle of data in temporary targets: GTT with ON COMMIT DELETE ROWS and local temporary table (which is
      transaction-scoped by default) keep rows only until commit, whereas GTT with ON COMMIT PRESERVE ROWS keeps them
      within the same session;
    * WITH NO DATA as the contrast case: such table must remain empty.
    NOTE: the fact that bulk insert path (and not regular record store) was taken can not be verified "directly",
    without trace/performance analysis, so this test checks only the observable contract (data completeness and
    lifecycles). Constraint enforcement is checked in test_with_data_bulk_insert_02.py.
NOTES:
    [06.10.2026] pzotov
    Test was generated by zcode.ai.
    Commit: 474cb872f93a11ec156ef43f57624ba9ea7f093f.
    See also: doc/sql.extensions/README.create_table_as_query.md
    Checked on 6.0.0.2199-bf94598.
"""

import pytest
from firebird.qa import *

db = db_factory(charset = 'utf8')

substitutions = [('[ \t]+', ' ')]
act = isql_act('db', substitutions = substitutions)

# 10k rows that have varying-length blobs make the test databases page-filling
# enough, so that both bulk and regular store paths do real page allocation work.
ROWS_TO_LOAD = 10000

DIFF_JOIN_PREDICATE = """
    s.cat  is distinct from c.cat
    or s.amt  is distinct from c.amt
    or s.vc   is distinct from c.vc
    or s.txt  is distinct from c.txt
    or s.bin  is distinct from c.bin
    or s.boo  is distinct from c.boo
    or s.tstz is distinct from c.tstz
"""

@pytest.mark.ai
@pytest.mark.version('>=6.0')
def test_1(act: Action):

    test_script = f"""
        set bail on;
        set list on;
        set autoddl off;
        commit;

        recreate table t_src (
            id   int not null primary key
           ,cat  smallint
           ,amt  numeric(12,2)
           ,vc   varchar(100) character set utf8
           ,txt  blob sub_type 1
           ,bin  blob sub_type 0
           ,boo  boolean
           ,tstz timestamp with time zone
        );

        set term ^;
        execute block as
            declare variable i integer;
        begin
            i = 0;
            while (i < {ROWS_TO_LOAD}) do begin
                insert into t_src values (
                    :i
                   ,mod(:i, 10)
                   ,case when mod(:i, 10) = 0 then null else :i * 1.25 end
                   ,case when mod(:i, 7) = 0 then null else 'строка_' || :i end
                   ,'txt_' || :i || '_' || lpad('x', 1 + mod(:i, 300), 'y')
                   ,gen_uuid()
                   ,case when mod(:i, 11) = 0 then null else mod(:i, 2) = 1 end
                   ,dateadd(:i minute to cast('2026-01-01 05:00:00 Asia/Novosibirsk' as timestamp with time zone))
                );
                i = i + 1;
            end
        end
        ^
        set term ;^
        commit;

        -- 1. Regular table.
        recreate table ctas_perm as select * from t_src with data;
        commit;
        select count(*) as count_src from t_src;
        select count(*) as count_perm from ctas_perm;
        select count(*) as diff_perm
        from t_src s join ctas_perm c on s.id = c.id
        where {DIFF_JOIN_PREDICATE};

        -- 2. Global temporary table, ON COMMIT PRESERVE ROWS.
        recreate global temporary table ctas_gtt_keep
            as select * from t_src with data
            on commit preserve rows;
        commit;
        select count(*) as count_gtt_keep from ctas_gtt_keep;
        select count(*) as diff_gtt_keep
        from t_src s join ctas_gtt_keep c on s.id = c.id
        where {DIFF_JOIN_PREDICATE};

        -- 3. WITH NO DATA: table must be empty.
        recreate table ctas_nodata as select * from t_src with no data;
        commit;
        select count(*) as count_nodata from ctas_nodata;

        -- 4. Global temporary table, ON COMMIT DELETE ROWS:
        -- rows exist only within the transaction that loaded them.
        drop table if exists ctas_gtt_drop;
        create global temporary table ctas_gtt_drop
            as select id, vc from t_src with data
            on commit delete rows;
        select count(*) as count_gtt_drop_pre from ctas_gtt_drop;
        commit;
        select count(*) as count_gtt_drop_post from ctas_gtt_drop;
        drop table ctas_gtt_drop;

        -- 5. Local temporary table (transaction-scoped by default):
        -- same lifecycle as in p.4.
        drop table if exists ctas_ltt;
        create local temporary table ctas_ltt
            as select id, vc from t_src with data;
        select count(*) as count_ltt_pre from ctas_ltt;
        commit;
        select count(*) as count_ltt_post from ctas_ltt;
        drop table ctas_ltt;
        commit;

        drop table ctas_perm;
        drop table ctas_gtt_keep;
        drop table ctas_nodata;
        drop table t_src;
        commit;
    """

    act.expected_stdout = f"""
        COUNT_SRC {ROWS_TO_LOAD}
        COUNT_PERM {ROWS_TO_LOAD}
        DIFF_PERM 0
        COUNT_GTT_KEEP {ROWS_TO_LOAD}
        DIFF_GTT_KEEP 0
        COUNT_NODATA 0
        COUNT_GTT_DROP_PRE {ROWS_TO_LOAD}
        COUNT_GTT_DROP_POST 0
        COUNT_LTT_PRE {ROWS_TO_LOAD}
        COUNT_LTT_POST 0
    """
    act.isql(switches = ['-q'], input = test_script, combine_output = True, charset = 'utf8')
    assert act.clean_stdout == act.clean_expected_stdout
