#coding:utf-8

"""
ID:          n/a
ISSUE:       https://github.com/FirebirdSQL/firebird/issues/9053
TITLE:       CTAS. Check that DDL triggers work properly when we use this feature.
DESCRIPTION:
NOTES:
    [03.07.2026] pzotov
    Checked on 6.0.0.2050-a4fa0b9.
"""
import pytest
from firebird.qa import *

db = db_factory()

substitutions = [('[ \t]+', ' '), ('DDL_BLOB_ID.*', '')]
act = isql_act('db', substitutions = substitutions)

@pytest.mark.version('>=6.0')
def test_1(act: Action):
    test_script = f"""
        set bail on;
        set list on;
        set blob all;
        set keep_tran on;
        set autoterm on;
        set autoddl off;

        recreate sequence g;
        create table log_ddl (
            id int generated by default as identity constraint pk_log_ddl primary key
            ,ddl_trigger_name varchar(64)
            ,event_type varchar(25) not null
            ,object_type varchar(25) not null
            ,ddl_event varchar(25) not null
            ,object_name varchar(64) not null
            ,dts timestamp default 'now'
            ,running_ddl blob sub_type text
        );
        commit;

        create procedure sp_log_ddl(a_trg_name varchar(64)) as
        begin
            if (rdb$get_context('USER_SESSION', 'SKIP_DDL_TRIGGER') is null) then
            begin
                insert into log_ddl (
                    ddl_trigger_name
                    ,event_type
                    ,object_type
                    ,ddl_event
                    ,object_name
                    ,running_ddl
                ) values(
                    upper(:a_trg_name)
                    ,rdb$get_context('DDL_TRIGGER', 'EVENT_TYPE')
                    ,rdb$get_context('DDL_TRIGGER', 'OBJECT_TYPE')
                    ,rdb$get_context('DDL_TRIGGER', 'DDL_EVENT')
                    ,rdb$get_context('DDL_TRIGGER', 'OBJECT_NAME')
                    ,rdb$get_context('DDL_TRIGGER', 'SQL_TEXT')
                );
            end
        end
        ;
        commit;

        execute block as
        begin
            rdb$set_context('USER_SESSION', 'SKIP_DDL_TRIGGER', '1');
        end
        ;

        create trigger trg_any_ddl_statement_before active before any ddl statement as
        begin
            execute procedure sp_log_ddl('trg_any_ddl_statement_before');
        end
        ;
        create trigger trg_any_ddl_statement_after active after any ddl statement as
        begin
            execute procedure sp_log_ddl('trg_any_ddl_statement_after');
        end
        ;
        create trigger trg_create_table_before active before CREATE TABLE as
        begin
            execute procedure sp_log_ddl('trg_create_table_before');
        end
        ;
        create trigger trg_create_table_after active after CREATE TABLE as
        begin
            execute procedure sp_log_ddl('trg_create_table_after');
        end
        ;

        execute block as
        begin
            -- logging must start after this:
            rdb$set_context('USER_SESSION', 'SKIP_DDL_TRIGGER', null);
        end
        ;

        execute block as
            declare s blob;
            declare n smallint = 2;
        begin
            s = 'create table ctas_regular(id) as (';
            while (n > 0) do
            begin
                  s = blob_append(s, 'select gen_id(g,1) from rdb$database');
                  if (n > 1) then
                    s = blob_append(s, ' union all ');
                else
                    s = blob_append(s, ') with data');
                n = n - 1;
            end
            execute statement s;
        end
        ;

        set count on;
        select
            id
            ,ddl_trigger_name
            ,ddl_event
            ,object_name
            ,running_ddl as ddl_blob_id
        from log_ddl
        order by id
        ;
    """

    act.expected_stdout = """
        ID 1
        DDL_TRIGGER_NAME TRG_CREATE_TABLE_BEFORE
        DDL_EVENT CREATE TABLE
        OBJECT_NAME CTAS_REGULAR
        DDL_BLOB_ID 80:0
        create table ctas_regular(id) as (select gen_id(g,1) from rdb$database union all select gen_id(g,1) from rdb$database) with data

        ID 2
        DDL_TRIGGER_NAME TRG_ANY_DDL_STATEMENT_BEFORE
        DDL_EVENT CREATE TABLE
        OBJECT_NAME CTAS_REGULAR
        DDL_BLOB_ID 80:1
        create table ctas_regular(id) as (select gen_id(g,1) from rdb$database union all select gen_id(g,1) from rdb$database) with data

        ID 3
        DDL_TRIGGER_NAME TRG_CREATE_TABLE_AFTER
        DDL_EVENT CREATE TABLE
        OBJECT_NAME CTAS_REGULAR
        DDL_BLOB_ID 80:2
        create table ctas_regular(id) as (select gen_id(g,1) from rdb$database union all select gen_id(g,1) from rdb$database) with data

        ID 4
        DDL_TRIGGER_NAME TRG_ANY_DDL_STATEMENT_AFTER
        DDL_EVENT CREATE TABLE
        OBJECT_NAME CTAS_REGULAR
        DDL_BLOB_ID 80:3
        create table ctas_regular(id) as (select gen_id(g,1) from rdb$database union all select gen_id(g,1) from rdb$database) with data

        Records affected: 4
    """
    act.isql(switches = ['-q'], input = test_script, combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
